/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetDccodeResponse implements Serializable {


    @JsonProperty("p_out_lov_dccode")
    @ColumnAlias("p_out_lov_dccode")
    private List<GetDccodeResponsePoutLovDccode> poutLovDccode;

    public List<GetDccodeResponsePoutLovDccode> getPoutLovDccode() {
        return this.poutLovDccode;
    }

    public void setPoutLovDccode(List<GetDccodeResponsePoutLovDccode> poutLovDccode) {
        this.poutLovDccode = poutLovDccode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetDccodeResponse)) return false;
        final GetDccodeResponse getDccodeResponse = (GetDccodeResponse) o;
        return Objects.equals(getPoutLovDccode(), getDccodeResponse.getPoutLovDccode());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutLovDccode());
    }
}