/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetFabdevreqdetResponsePoutYarndet implements Serializable {


    @JsonProperty("INIYRNSEQ")
    @ColumnAlias("INIYRNSEQ")
    private Byte iniyrnseq;

    @JsonProperty("YRNCNT")
    @ColumnAlias("YRNCNT")
    private String yrncnt;

    @JsonProperty("YRNCPS")
    @ColumnAlias("YRNCPS")
    private String yrncps;

    @JsonProperty("YRNCLR")
    @ColumnAlias("YRNCLR")
    private String yrnclr;

    @JsonProperty("YRNCDES_LOV")
    @ColumnAlias("YRNCDES_LOV")
    private String yrncdesLov;

    @JsonProperty("YRNCDES")
    @ColumnAlias("YRNCDES")
    private String yrncdes;

    @JsonProperty("CLRREF")
    @ColumnAlias("CLRREF")
    private String clrref;

    @JsonProperty("YRNQLTY")
    @ColumnAlias("YRNQLTY")
    private String yrnqlty;

    @JsonProperty("YRNSUBQLTYA")
    @ColumnAlias("YRNSUBQLTYA")
    private String yrnsubqltya;

    @JsonProperty("YRNSUBQLTYADESC")
    @ColumnAlias("YRNSUBQLTYADESC")
    private String yrnsubqltyadesc;

    @JsonProperty("YRNSUBQLTYB")
    @ColumnAlias("YRNSUBQLTYB")
    private String yrnsubqltyb;

    @JsonProperty("YRNSUBQLTYBDESC")
    @ColumnAlias("YRNSUBQLTYBDESC")
    private String yrnsubqltybdesc;

    @JsonProperty("YRNFFCOD")
    @ColumnAlias("YRNFFCOD")
    private String yrnffcod;

    public Byte getIniyrnseq() {
        return this.iniyrnseq;
    }

    public void setIniyrnseq(Byte iniyrnseq) {
        this.iniyrnseq = iniyrnseq;
    }

    public String getYrncnt() {
        return this.yrncnt;
    }

    public void setYrncnt(String yrncnt) {
        this.yrncnt = yrncnt;
    }

    public String getYrncps() {
        return this.yrncps;
    }

    public void setYrncps(String yrncps) {
        this.yrncps = yrncps;
    }

    public String getYrnclr() {
        return this.yrnclr;
    }

    public void setYrnclr(String yrnclr) {
        this.yrnclr = yrnclr;
    }

    public String getYrncdesLov() {
        return this.yrncdesLov;
    }

    public void setYrncdesLov(String yrncdesLov) {
        this.yrncdesLov = yrncdesLov;
    }

    public String getYrncdes() {
        return this.yrncdes;
    }

    public void setYrncdes(String yrncdes) {
        this.yrncdes = yrncdes;
    }

    public String getClrref() {
        return this.clrref;
    }

    public void setClrref(String clrref) {
        this.clrref = clrref;
    }

    public String getYrnqlty() {
        return this.yrnqlty;
    }

    public void setYrnqlty(String yrnqlty) {
        this.yrnqlty = yrnqlty;
    }

    public String getYrnsubqltya() {
        return this.yrnsubqltya;
    }

    public void setYrnsubqltya(String yrnsubqltya) {
        this.yrnsubqltya = yrnsubqltya;
    }

    public String getYrnsubqltyadesc() {
        return this.yrnsubqltyadesc;
    }

    public void setYrnsubqltyadesc(String yrnsubqltyadesc) {
        this.yrnsubqltyadesc = yrnsubqltyadesc;
    }

    public String getYrnsubqltyb() {
        return this.yrnsubqltyb;
    }

    public void setYrnsubqltyb(String yrnsubqltyb) {
        this.yrnsubqltyb = yrnsubqltyb;
    }

    public String getYrnsubqltybdesc() {
        return this.yrnsubqltybdesc;
    }

    public void setYrnsubqltybdesc(String yrnsubqltybdesc) {
        this.yrnsubqltybdesc = yrnsubqltybdesc;
    }

    public String getYrnffcod() {
        return this.yrnffcod;
    }

    public void setYrnffcod(String yrnffcod) {
        this.yrnffcod = yrnffcod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetFabdevreqdetResponsePoutYarndet)) return false;
        final GetFabdevreqdetResponsePoutYarndet getFabdevreqdetResponsePoutYarndet = (GetFabdevreqdetResponsePoutYarndet) o;
        return Objects.equals(getIniyrnseq(), getFabdevreqdetResponsePoutYarndet.getIniyrnseq()) &&
                Objects.equals(getYrncnt(), getFabdevreqdetResponsePoutYarndet.getYrncnt()) &&
                Objects.equals(getYrncps(), getFabdevreqdetResponsePoutYarndet.getYrncps()) &&
                Objects.equals(getYrnclr(), getFabdevreqdetResponsePoutYarndet.getYrnclr()) &&
                Objects.equals(getYrncdesLov(), getFabdevreqdetResponsePoutYarndet.getYrncdesLov()) &&
                Objects.equals(getYrncdes(), getFabdevreqdetResponsePoutYarndet.getYrncdes()) &&
                Objects.equals(getClrref(), getFabdevreqdetResponsePoutYarndet.getClrref()) &&
                Objects.equals(getYrnqlty(), getFabdevreqdetResponsePoutYarndet.getYrnqlty()) &&
                Objects.equals(getYrnsubqltya(), getFabdevreqdetResponsePoutYarndet.getYrnsubqltya()) &&
                Objects.equals(getYrnsubqltyadesc(), getFabdevreqdetResponsePoutYarndet.getYrnsubqltyadesc()) &&
                Objects.equals(getYrnsubqltyb(), getFabdevreqdetResponsePoutYarndet.getYrnsubqltyb()) &&
                Objects.equals(getYrnsubqltybdesc(), getFabdevreqdetResponsePoutYarndet.getYrnsubqltybdesc()) &&
                Objects.equals(getYrnffcod(), getFabdevreqdetResponsePoutYarndet.getYrnffcod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIniyrnseq(),
                getYrncnt(),
                getYrncps(),
                getYrnclr(),
                getYrncdesLov(),
                getYrncdes(),
                getClrref(),
                getYrnqlty(),
                getYrnsubqltya(),
                getYrnsubqltyadesc(),
                getYrnsubqltyb(),
                getYrnsubqltybdesc(),
                getYrnffcod());
    }
}