/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetFabtypResponsePoutLovFabtyp implements Serializable {


    @JsonProperty("FABTYP")
    @ColumnAlias("FABTYP")
    private String fabtyp;

    @JsonProperty("FABDES")
    @ColumnAlias("FABDES")
    private String fabdes;

    public String getFabtyp() {
        return this.fabtyp;
    }

    public void setFabtyp(String fabtyp) {
        this.fabtyp = fabtyp;
    }

    public String getFabdes() {
        return this.fabdes;
    }

    public void setFabdes(String fabdes) {
        this.fabdes = fabdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetFabtypResponsePoutLovFabtyp)) return false;
        final GetFabtypResponsePoutLovFabtyp getFabtypResponsePoutLovFabtyp = (GetFabtypResponsePoutLovFabtyp) o;
        return Objects.equals(getFabtyp(), getFabtypResponsePoutLovFabtyp.getFabtyp()) &&
                Objects.equals(getFabdes(), getFabtypResponsePoutLovFabtyp.getFabdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFabtyp(),
                getFabdes());
    }
}