/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcTt130pk0FabdevlibClicodResponse implements Serializable {


    @ColumnAlias("poutClient")
    private List<GetProcTt130pk0FabdevlibClicodResponsePoutClient> poutClient;

    public List<GetProcTt130pk0FabdevlibClicodResponsePoutClient> getPoutClient() {
        return this.poutClient;
    }

    public void setPoutClient(List<GetProcTt130pk0FabdevlibClicodResponsePoutClient> poutClient) {
        this.poutClient = poutClient;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcTt130pk0FabdevlibClicodResponse)) return false;
        final GetProcTt130pk0FabdevlibClicodResponse getProcTt130pk0fabdevlibClicodResponse = (GetProcTt130pk0FabdevlibClicodResponse) o;
        return Objects.equals(getPoutClient(), getProcTt130pk0fabdevlibClicodResponse.getPoutClient());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutClient());
    }
}