/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcTt130pk0FabdevlibClicodResponsePoutClient implements Serializable {


    @ColumnAlias("CLICOD")
    private String clicod;

    @ColumnAlias("CLINAM")
    private String clinam;

    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    public String getClinam() {
        return this.clinam;
    }

    public void setClinam(String clinam) {
        this.clinam = clinam;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcTt130pk0FabdevlibClicodResponsePoutClient)) return false;
        final GetProcTt130pk0FabdevlibClicodResponsePoutClient getProcTt130pk0fabdevlibClicodResponsePoutClient = (GetProcTt130pk0FabdevlibClicodResponsePoutClient) o;
        return Objects.equals(getClicod(), getProcTt130pk0fabdevlibClicodResponsePoutClient.getClicod()) &&
                Objects.equals(getClinam(), getProcTt130pk0fabdevlibClicodResponsePoutClient.getClinam());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getClicod(),
                getClinam());
    }
}