/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetYrnqltyResponsePoutLovYrnqlty implements Serializable {


    @JsonProperty("NYRNQLTY")
    @ColumnAlias("NYRNQLTY")
    private String nyrnqlty;

    @JsonProperty("NYRNQLTYDES")
    @ColumnAlias("NYRNQLTYDES")
    private String nyrnqltydes;

    public String getNyrnqlty() {
        return this.nyrnqlty;
    }

    public void setNyrnqlty(String nyrnqlty) {
        this.nyrnqlty = nyrnqlty;
    }

    public String getNyrnqltydes() {
        return this.nyrnqltydes;
    }

    public void setNyrnqltydes(String nyrnqltydes) {
        this.nyrnqltydes = nyrnqltydes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetYrnqltyResponsePoutLovYrnqlty)) return false;
        final GetYrnqltyResponsePoutLovYrnqlty getYrnqltyResponsePoutLovYrnqlty = (GetYrnqltyResponsePoutLovYrnqlty) o;
        return Objects.equals(getNyrnqlty(), getYrnqltyResponsePoutLovYrnqlty.getNyrnqlty()) &&
                Objects.equals(getNyrnqltydes(), getYrnqltyResponsePoutLovYrnqlty.getNyrnqltydes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNyrnqlty(),
                getNyrnqltydes());
    }
}