/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetYrnclrResponsePoutLovYrnclr implements Serializable {


    @JsonProperty("NYRNCLR")
    @ColumnAlias("NYRNCLR")
    private String nyrnclr;

    @JsonProperty("NYRNCDES")
    @ColumnAlias("NYRNCDES")
    private String nyrncdes;

    @JsonProperty("YRNCDES_LOV")
    @ColumnAlias("YRNCDES_LOV")
    private String yrncdesLov;

    public String getNyrnclr() {
        return this.nyrnclr;
    }

    public void setNyrnclr(String nyrnclr) {
        this.nyrnclr = nyrnclr;
    }

    public String getNyrncdes() {
        return this.nyrncdes;
    }

    public void setNyrncdes(String nyrncdes) {
        this.nyrncdes = nyrncdes;
    }

    public String getYrncdesLov() {
        return this.yrncdesLov;
    }

    public void setYrncdesLov(String yrncdesLov) {
        this.yrncdesLov = yrncdesLov;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetYrnclrResponsePoutLovYrnclr)) return false;
        final GetYrnclrResponsePoutLovYrnclr getYrnclrResponsePoutLovYrnclr = (GetYrnclrResponsePoutLovYrnclr) o;
        return Objects.equals(getNyrnclr(), getYrnclrResponsePoutLovYrnclr.getNyrnclr()) &&
                Objects.equals(getNyrncdes(), getYrnclrResponsePoutLovYrnclr.getNyrncdes()) &&
                Objects.equals(getYrncdesLov(), getYrnclrResponsePoutLovYrnclr.getYrncdesLov());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNyrnclr(),
                getNyrncdes(),
                getYrncdesLov());
    }
}