/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetYrnsubqltyaResponsePoutLovYrnsubqlty implements Serializable {


    @JsonProperty("SUBQLTYCOD")
    @ColumnAlias("SUBQLTYCOD")
    private String subqltycod;

    @JsonProperty("SUBQLTYDES")
    @ColumnAlias("SUBQLTYDES")
    private String subqltydes;

    @JsonProperty("LABEL")
    @ColumnAlias("LABEL")
    private String label;

    public String getSubqltycod() {
        return this.subqltycod;
    }

    public void setSubqltycod(String subqltycod) {
        this.subqltycod = subqltycod;
    }

    public String getSubqltydes() {
        return this.subqltydes;
    }

    public void setSubqltydes(String subqltydes) {
        this.subqltydes = subqltydes;
    }

    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetYrnsubqltyaResponsePoutLovYrnsubqlty)) return false;
        final GetYrnsubqltyaResponsePoutLovYrnsubqlty getYrnsubqltyaResponsePoutLovYrnsubqlty = (GetYrnsubqltyaResponsePoutLovYrnsubqlty) o;
        return Objects.equals(getSubqltycod(), getYrnsubqltyaResponsePoutLovYrnsubqlty.getSubqltycod()) &&
                Objects.equals(getSubqltydes(), getYrnsubqltyaResponsePoutLovYrnsubqlty.getSubqltydes()) &&
                Objects.equals(getLabel(), getYrnsubqltyaResponsePoutLovYrnsubqlty.getLabel());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSubqltycod(),
                getSubqltydes(),
                getLabel());
    }
}