/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetYrnsubqltybResponse implements Serializable {


    @JsonProperty("p_out_lov_yrnsubqlty")
    @ColumnAlias("p_out_lov_yrnsubqlty")
    private List<GetYrnsubqltybResponsePoutLovYrnsubqlty> poutLovYrnsubqlty;

    public List<GetYrnsubqltybResponsePoutLovYrnsubqlty> getPoutLovYrnsubqlty() {
        return this.poutLovYrnsubqlty;
    }

    public void setPoutLovYrnsubqlty(List<GetYrnsubqltybResponsePoutLovYrnsubqlty> poutLovYrnsubqlty) {
        this.poutLovYrnsubqlty = poutLovYrnsubqlty;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetYrnsubqltybResponse)) return false;
        final GetYrnsubqltybResponse getYrnsubqltybResponse = (GetYrnsubqltybResponse) o;
        return Objects.equals(getPoutLovYrnsubqlty(), getYrnsubqltybResponse.getPoutLovYrnsubqlty());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutLovYrnsubqlty());
    }
}