/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcTt130pk0FabdevlibGetYrnCpsResponsePoutYrnCps implements Serializable {


    @ColumnAlias("FCPSDES")
    private String fcpsdes;

    @ColumnAlias("DESCRIPTION")
    private String description;

    public String getFcpsdes() {
        return this.fcpsdes;
    }

    public void setFcpsdes(String fcpsdes) {
        this.fcpsdes = fcpsdes;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcTt130pk0FabdevlibGetYrnCpsResponsePoutYrnCps)) return false;
        final ProcTt130pk0FabdevlibGetYrnCpsResponsePoutYrnCps procTt130pk0fabdevlibGetYrnCpsResponsePoutYrnCps = (ProcTt130pk0FabdevlibGetYrnCpsResponsePoutYrnCps) o;
        return Objects.equals(getFcpsdes(), procTt130pk0fabdevlibGetYrnCpsResponsePoutYrnCps.getFcpsdes()) &&
                Objects.equals(getDescription(), procTt130pk0fabdevlibGetYrnCpsResponsePoutYrnCps.getDescription());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFcpsdes(),
                getDescription());
    }
}