/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutYarndet implements Serializable {


    @ColumnAlias("INIYRNSEQ")
    private Byte iniyrnseq;

    @ColumnAlias("YRNCNT")
    private String yrncnt;

    @ColumnAlias("YRNCPS")
    private String yrncps;

    @ColumnAlias("YRNCLR")
    private String yrnclr;

    @ColumnAlias("YRNCDES")
    private String yrncdes;

    @ColumnAlias("CLRREF")
    private String clrref;

    @ColumnAlias("YRNQLTY")
    private String yrnqlty;

    @ColumnAlias("YRNSUBQLTYA")
    private String yrnsubqltya;

    @ColumnAlias("YRNSUBQLTYADESC")
    private String yrnsubqltyadesc;

    @ColumnAlias("YRNSUBQLTYB")
    private String yrnsubqltyb;

    @ColumnAlias("YRNSUBQLTYBDESC")
    private String yrnsubqltybdesc;

    @ColumnAlias("YRNFFCOD")
    private String yrnffcod;

    public Byte getIniyrnseq() {
        return this.iniyrnseq;
    }

    public void setIniyrnseq(Byte iniyrnseq) {
        this.iniyrnseq = iniyrnseq;
    }

    public String getYrncnt() {
        return this.yrncnt;
    }

    public void setYrncnt(String yrncnt) {
        this.yrncnt = yrncnt;
    }

    public String getYrncps() {
        return this.yrncps;
    }

    public void setYrncps(String yrncps) {
        this.yrncps = yrncps;
    }

    public String getYrnclr() {
        return this.yrnclr;
    }

    public void setYrnclr(String yrnclr) {
        this.yrnclr = yrnclr;
    }

    public String getYrncdes() {
        return this.yrncdes;
    }

    public void setYrncdes(String yrncdes) {
        this.yrncdes = yrncdes;
    }

    public String getClrref() {
        return this.clrref;
    }

    public void setClrref(String clrref) {
        this.clrref = clrref;
    }

    public String getYrnqlty() {
        return this.yrnqlty;
    }

    public void setYrnqlty(String yrnqlty) {
        this.yrnqlty = yrnqlty;
    }

    public String getYrnsubqltya() {
        return this.yrnsubqltya;
    }

    public void setYrnsubqltya(String yrnsubqltya) {
        this.yrnsubqltya = yrnsubqltya;
    }

    public String getYrnsubqltyadesc() {
        return this.yrnsubqltyadesc;
    }

    public void setYrnsubqltyadesc(String yrnsubqltyadesc) {
        this.yrnsubqltyadesc = yrnsubqltyadesc;
    }

    public String getYrnsubqltyb() {
        return this.yrnsubqltyb;
    }

    public void setYrnsubqltyb(String yrnsubqltyb) {
        this.yrnsubqltyb = yrnsubqltyb;
    }

    public String getYrnsubqltybdesc() {
        return this.yrnsubqltybdesc;
    }

    public void setYrnsubqltybdesc(String yrnsubqltybdesc) {
        this.yrnsubqltybdesc = yrnsubqltybdesc;
    }

    public String getYrnffcod() {
        return this.yrnffcod;
    }

    public void setYrnffcod(String yrnffcod) {
        this.yrnffcod = yrnffcod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutYarndet)) return false;
        final ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutYarndet procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet = (ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutYarndet) o;
        return Objects.equals(getIniyrnseq(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getIniyrnseq()) &&
                Objects.equals(getYrncnt(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getYrncnt()) &&
                Objects.equals(getYrncps(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getYrncps()) &&
                Objects.equals(getYrnclr(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getYrnclr()) &&
                Objects.equals(getYrncdes(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getYrncdes()) &&
                Objects.equals(getClrref(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getClrref()) &&
                Objects.equals(getYrnqlty(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getYrnqlty()) &&
                Objects.equals(getYrnsubqltya(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getYrnsubqltya()) &&
                Objects.equals(getYrnsubqltyadesc(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getYrnsubqltyadesc()) &&
                Objects.equals(getYrnsubqltyb(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getYrnsubqltyb()) &&
                Objects.equals(getYrnsubqltybdesc(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getYrnsubqltybdesc()) &&
                Objects.equals(getYrnffcod(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutYarndet.getYrnffcod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIniyrnseq(),
                getYrncnt(),
                getYrncps(),
                getYrnclr(),
                getYrncdes(),
                getClrref(),
                getYrnqlty(),
                getYrnsubqltya(),
                getYrnsubqltyadesc(),
                getYrnsubqltyb(),
                getYrnsubqltybdesc(),
                getYrnffcod());
    }
}