/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcKn1620pk0CcfmqryQryCcfResponse implements Serializable {


    @ColumnAlias("p_out_ccflist")
    private List<ProcKn1620pk0CcfmqryQryCcfResponsePoutCcflist> poutCcflist;

    public List<ProcKn1620pk0CcfmqryQryCcfResponsePoutCcflist> getPoutCcflist() {
        return this.poutCcflist;
    }

    public void setPoutCcflist(List<ProcKn1620pk0CcfmqryQryCcfResponsePoutCcflist> poutCcflist) {
        this.poutCcflist = poutCcflist;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcKn1620pk0CcfmqryQryCcfResponse)) return false;
        final ProcKn1620pk0CcfmqryQryCcfResponse procKn1620pk0ccfmqryQryCcfResponse = (ProcKn1620pk0CcfmqryQryCcfResponse) o;
        return Objects.equals(getPoutCcflist(), procKn1620pk0ccfmqryQryCcfResponse.getPoutCcflist());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutCcflist());
    }
}