/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf020pk0getClrOptResponse implements Serializable {


    @ColumnAlias("p_out_lov")
    private List<ProcRf020pk0getClrOptResponsePoutLov> poutLov;

    public List<ProcRf020pk0getClrOptResponsePoutLov> getPoutLov() {
        return this.poutLov;
    }

    public void setPoutLov(List<ProcRf020pk0getClrOptResponsePoutLov> poutLov) {
        this.poutLov = poutLov;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf020pk0getClrOptResponse)) return false;
        final ProcRf020pk0getClrOptResponse procRf020pk0getClrOptResponse = (ProcRf020pk0getClrOptResponse) o;
        return Objects.equals(getPoutLov(), procRf020pk0getClrOptResponse.getPoutLov());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutLov());
    }
}