/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet implements Serializable {


    @ColumnAlias("MINTFABCERTNO")
    private String mintfabcertno;

    @ColumnAlias("MCCF_ORDNUM")
    private String mccfOrdnum;

    @ColumnAlias("MCCF_FABSEQ")
    private Byte mccfFabseq;

    @ColumnAlias("MCCF_FABDET")
    private String mccfFabdet;

    @ColumnAlias("CCFMATCHCAT")
    private String ccfmatchcat;

    @ColumnAlias("CCFFILTER")
    private String ccffilter;

    public String getMintfabcertno() {
        return this.mintfabcertno;
    }

    public void setMintfabcertno(String mintfabcertno) {
        this.mintfabcertno = mintfabcertno;
    }

    public String getMccfOrdnum() {
        return this.mccfOrdnum;
    }

    public void setMccfOrdnum(String mccfOrdnum) {
        this.mccfOrdnum = mccfOrdnum;
    }

    public Byte getMccfFabseq() {
        return this.mccfFabseq;
    }

    public void setMccfFabseq(Byte mccfFabseq) {
        this.mccfFabseq = mccfFabseq;
    }

    public String getMccfFabdet() {
        return this.mccfFabdet;
    }

    public void setMccfFabdet(String mccfFabdet) {
        this.mccfFabdet = mccfFabdet;
    }

    public String getCcfmatchcat() {
        return this.ccfmatchcat;
    }

    public void setCcfmatchcat(String ccfmatchcat) {
        this.ccfmatchcat = ccfmatchcat;
    }

    public String getCcffilter() {
        return this.ccffilter;
    }

    public void setCcffilter(String ccffilter) {
        this.ccffilter = ccffilter;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet)) return false;
        final ProcKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet procKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet = (ProcKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet) o;
        return Objects.equals(getMintfabcertno(), procKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet.getMintfabcertno()) &&
                Objects.equals(getMccfOrdnum(), procKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet.getMccfOrdnum()) &&
                Objects.equals(getMccfFabseq(), procKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet.getMccfFabseq()) &&
                Objects.equals(getMccfFabdet(), procKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet.getMccfFabdet()) &&
                Objects.equals(getCcfmatchcat(), procKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet.getCcfmatchcat()) &&
                Objects.equals(getCcffilter(), procKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet.getCcffilter());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getMintfabcertno(),
                getMccfOrdnum(),
                getMccfFabseq(),
                getMccfFabdet(),
                getCcfmatchcat(),
                getCcffilter());
    }
}