/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcKn1610pk0ExcccfGetRelatedMatrixResponsePoutOrderList implements Serializable {


    @ColumnAlias("TEMPLATESEQ")
    private String templateseq;

    @ColumnAlias("INTFABCERTNO")
    private String intfabcertno;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("FABTYP")
    private String fabtyp;

    @ColumnAlias("FABWGT")
    private Short fabwgt;

    @ColumnAlias("CALSTN")
    private String calstn;

    @ColumnAlias("CERTSTS")
    private String certsts;

    @ColumnAlias("YRNDET")
    private String yrndet;

    public String getTemplateseq() {
        return this.templateseq;
    }

    public void setTemplateseq(String templateseq) {
        this.templateseq = templateseq;
    }

    public String getIntfabcertno() {
        return this.intfabcertno;
    }

    public void setIntfabcertno(String intfabcertno) {
        this.intfabcertno = intfabcertno;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public String getFabtyp() {
        return this.fabtyp;
    }

    public void setFabtyp(String fabtyp) {
        this.fabtyp = fabtyp;
    }

    public Short getFabwgt() {
        return this.fabwgt;
    }

    public void setFabwgt(Short fabwgt) {
        this.fabwgt = fabwgt;
    }

    public String getCalstn() {
        return this.calstn;
    }

    public void setCalstn(String calstn) {
        this.calstn = calstn;
    }

    public String getCertsts() {
        return this.certsts;
    }

    public void setCertsts(String certsts) {
        this.certsts = certsts;
    }

    public String getYrndet() {
        return this.yrndet;
    }

    public void setYrndet(String yrndet) {
        this.yrndet = yrndet;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcKn1610pk0ExcccfGetRelatedMatrixResponsePoutOrderList)) return false;
        final ProcKn1610pk0ExcccfGetRelatedMatrixResponsePoutOrderList procKn1610pk0excccfGetRelatedMatrixResponsePoutOrderList = (ProcKn1610pk0ExcccfGetRelatedMatrixResponsePoutOrderList) o;
        return Objects.equals(getTemplateseq(), procKn1610pk0excccfGetRelatedMatrixResponsePoutOrderList.getTemplateseq()) &&
                Objects.equals(getIntfabcertno(), procKn1610pk0excccfGetRelatedMatrixResponsePoutOrderList.getIntfabcertno()) &&
                Objects.equals(getOrdnum(), procKn1610pk0excccfGetRelatedMatrixResponsePoutOrderList.getOrdnum()) &&
                Objects.equals(getFabseq(), procKn1610pk0excccfGetRelatedMatrixResponsePoutOrderList.getFabseq()) &&
                Objects.equals(getFabtyp(), procKn1610pk0excccfGetRelatedMatrixResponsePoutOrderList.getFabtyp()) &&
                Objects.equals(getFabwgt(), procKn1610pk0excccfGetRelatedMatrixResponsePoutOrderList.getFabwgt()) &&
                Objects.equals(getCalstn(), procKn1610pk0excccfGetRelatedMatrixResponsePoutOrderList.getCalstn()) &&
                Objects.equals(getCertsts(), procKn1610pk0excccfGetRelatedMatrixResponsePoutOrderList.getCertsts()) &&
                Objects.equals(getYrndet(), procKn1610pk0excccfGetRelatedMatrixResponsePoutOrderList.getYrndet());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTemplateseq(),
                getIntfabcertno(),
                getOrdnum(),
                getFabseq(),
                getFabtyp(),
                getFabwgt(),
                getCalstn(),
                getCertsts(),
                getYrndet());
    }
}