/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcKn1620pk0CcfmqryQryCcfResponsePoutCcflist implements Serializable {


    @ColumnAlias("SINTFABCERTNO")
    private String sintfabcertno;

    @ColumnAlias("SCCF_ORDNUM")
    private String sccfOrdnum;

    @ColumnAlias("SCCF_FABSEQ")
    private Byte sccfFabseq;

    @ColumnAlias("SCCF_FABDET")
    private String sccfFabdet;

    @ColumnAlias("DINTFABCERTNO")
    private String dintfabcertno;

    @ColumnAlias("DCCF_ORDNUM")
    private String dccfOrdnum;

    @ColumnAlias("DCCF_FABSEQ")
    private Byte dccfFabseq;

    @ColumnAlias("DCCF_FABDET")
    private String dccfFabdet;

    @ColumnAlias("CCFFILTER")
    private String ccffilter;

    public String getSintfabcertno() {
        return this.sintfabcertno;
    }

    public void setSintfabcertno(String sintfabcertno) {
        this.sintfabcertno = sintfabcertno;
    }

    public String getSccfOrdnum() {
        return this.sccfOrdnum;
    }

    public void setSccfOrdnum(String sccfOrdnum) {
        this.sccfOrdnum = sccfOrdnum;
    }

    public Byte getSccfFabseq() {
        return this.sccfFabseq;
    }

    public void setSccfFabseq(Byte sccfFabseq) {
        this.sccfFabseq = sccfFabseq;
    }

    public String getSccfFabdet() {
        return this.sccfFabdet;
    }

    public void setSccfFabdet(String sccfFabdet) {
        this.sccfFabdet = sccfFabdet;
    }

    public String getDintfabcertno() {
        return this.dintfabcertno;
    }

    public void setDintfabcertno(String dintfabcertno) {
        this.dintfabcertno = dintfabcertno;
    }

    public String getDccfOrdnum() {
        return this.dccfOrdnum;
    }

    public void setDccfOrdnum(String dccfOrdnum) {
        this.dccfOrdnum = dccfOrdnum;
    }

    public Byte getDccfFabseq() {
        return this.dccfFabseq;
    }

    public void setDccfFabseq(Byte dccfFabseq) {
        this.dccfFabseq = dccfFabseq;
    }

    public String getDccfFabdet() {
        return this.dccfFabdet;
    }

    public void setDccfFabdet(String dccfFabdet) {
        this.dccfFabdet = dccfFabdet;
    }

    public String getCcffilter() {
        return this.ccffilter;
    }

    public void setCcffilter(String ccffilter) {
        this.ccffilter = ccffilter;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcKn1620pk0CcfmqryQryCcfResponsePoutCcflist)) return false;
        final ProcKn1620pk0CcfmqryQryCcfResponsePoutCcflist procKn1620pk0ccfmqryQryCcfResponsePoutCcflist = (ProcKn1620pk0CcfmqryQryCcfResponsePoutCcflist) o;
        return Objects.equals(getSintfabcertno(), procKn1620pk0ccfmqryQryCcfResponsePoutCcflist.getSintfabcertno()) &&
                Objects.equals(getSccfOrdnum(), procKn1620pk0ccfmqryQryCcfResponsePoutCcflist.getSccfOrdnum()) &&
                Objects.equals(getSccfFabseq(), procKn1620pk0ccfmqryQryCcfResponsePoutCcflist.getSccfFabseq()) &&
                Objects.equals(getSccfFabdet(), procKn1620pk0ccfmqryQryCcfResponsePoutCcflist.getSccfFabdet()) &&
                Objects.equals(getDintfabcertno(), procKn1620pk0ccfmqryQryCcfResponsePoutCcflist.getDintfabcertno()) &&
                Objects.equals(getDccfOrdnum(), procKn1620pk0ccfmqryQryCcfResponsePoutCcflist.getDccfOrdnum()) &&
                Objects.equals(getDccfFabseq(), procKn1620pk0ccfmqryQryCcfResponsePoutCcflist.getDccfFabseq()) &&
                Objects.equals(getDccfFabdet(), procKn1620pk0ccfmqryQryCcfResponsePoutCcflist.getDccfFabdet()) &&
                Objects.equals(getCcffilter(), procKn1620pk0ccfmqryQryCcfResponsePoutCcflist.getCcffilter());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSintfabcertno(),
                getSccfOrdnum(),
                getSccfFabseq(),
                getSccfFabdet(),
                getDintfabcertno(),
                getDccfOrdnum(),
                getDccfFabseq(),
                getDccfFabdet(),
                getCcffilter());
    }
}