/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcKn1610pk0ExcccfGetCcflistResponse implements Serializable {


    @ColumnAlias("p_outFabCertList")
    private List<ProcKn1610pk0ExcccfGetCcflistResponsePoutFabCertList> poutFabCertList;

    public List<ProcKn1610pk0ExcccfGetCcflistResponsePoutFabCertList> getPoutFabCertList() {
        return this.poutFabCertList;
    }

    public void setPoutFabCertList(List<ProcKn1610pk0ExcccfGetCcflistResponsePoutFabCertList> poutFabCertList) {
        this.poutFabCertList = poutFabCertList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcKn1610pk0ExcccfGetCcflistResponse)) return false;
        final ProcKn1610pk0ExcccfGetCcflistResponse procKn1610pk0excccfGetCcflistResponse = (ProcKn1610pk0ExcccfGetCcflistResponse) o;
        return Objects.equals(getPoutFabCertList(), procKn1610pk0excccfGetCcflistResponse.getPoutFabCertList());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutFabCertList());
    }
}