/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutFabdet implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("FABDES")
    private String fabdes;

    @ColumnAlias("FABWGT")
    private Short fabwgt;

    @ColumnAlias("BSFFABWGT")
    private Short bsffabwgt;

    @ColumnAlias("KMCHTYP")
    private String kmchtyp;

    @ColumnAlias("MCHGAU")
    private Short mchgau;

    @ColumnAlias("INSIDE")
    private String inside;

    @ColumnAlias("INSIDEDES")
    private String insidedes;

    @ColumnAlias("OUTSIDE")
    private String outside;

    @ColumnAlias("OUTSIDEDES")
    private String outsidedes;

    @ColumnAlias("SPFINISH")
    private String spfinish;

    @ColumnAlias("SPFINISHDES")
    private String spfinishdes;

    @ColumnAlias("SPFINISHDES2")
    private String spfinishdes2;

    @ColumnAlias("ENZYME")
    private String enzyme;

    @ColumnAlias("ENZYMEDES")
    private String enzymedes;

    @ColumnAlias("BDSZE")
    private String bdsze;

    @ColumnAlias("STR")
    private String str;

    @ColumnAlias("STRDES")
    private String strdes;

    @ColumnAlias("STRIPEID")
    private String stripeid;

    @ColumnAlias("FABCPS_BSF")
    private String fabcpsBsf;

    @ColumnAlias("FABCPS")
    private String fabcps;

    @ColumnAlias("THERMOBD_IND")
    private String thermobdInd;

    @ColumnAlias("LDECOROUTE")
    private String ldecoroute;

    @ColumnAlias("SDECOROUTE")
    private String sdecoroute;

    @ColumnAlias("DCCODE")
    private String dccode;

    @ColumnAlias("DCCODELDESC")
    private String dccodeldesc;

    @ColumnAlias("DCCODELABEL")
    private String dccodelabel;

    @ColumnAlias("FABDCODELIST")
    private String fabdcodelist;

    @ColumnAlias("KNSHADETYPDES")
    private String knshadetypdes;

    @ColumnAlias("KNSHADETYP")
    private String knshadetyp;

    @ColumnAlias("CPSTYPA")
    private String cpstypa;

    @ColumnAlias("CPSTYPADES")
    private String cpstypades;

    @ColumnAlias("CPSTYPAFROM")
    private BigInteger cpstypafrom;

    @ColumnAlias("CPSTYPB")
    private String cpstypb;

    @ColumnAlias("CPSTYPBDES")
    private String cpstypbdes;

    @ColumnAlias("CPSTYPBFROM")
    private BigInteger cpstypbfrom;

    @ColumnAlias("CPSTYPC")
    private String cpstypc;

    @ColumnAlias("CPSTYPCDES")
    private String cpstypcdes;

    @ColumnAlias("CPSTYPCFROM")
    private BigInteger cpstypcfrom;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public String getFabdes() {
        return this.fabdes;
    }

    public void setFabdes(String fabdes) {
        this.fabdes = fabdes;
    }

    public Short getFabwgt() {
        return this.fabwgt;
    }

    public void setFabwgt(Short fabwgt) {
        this.fabwgt = fabwgt;
    }

    public Short getBsffabwgt() {
        return this.bsffabwgt;
    }

    public void setBsffabwgt(Short bsffabwgt) {
        this.bsffabwgt = bsffabwgt;
    }

    public String getKmchtyp() {
        return this.kmchtyp;
    }

    public void setKmchtyp(String kmchtyp) {
        this.kmchtyp = kmchtyp;
    }

    public Short getMchgau() {
        return this.mchgau;
    }

    public void setMchgau(Short mchgau) {
        this.mchgau = mchgau;
    }

    public String getInside() {
        return this.inside;
    }

    public void setInside(String inside) {
        this.inside = inside;
    }

    public String getInsidedes() {
        return this.insidedes;
    }

    public void setInsidedes(String insidedes) {
        this.insidedes = insidedes;
    }

    public String getOutside() {
        return this.outside;
    }

    public void setOutside(String outside) {
        this.outside = outside;
    }

    public String getOutsidedes() {
        return this.outsidedes;
    }

    public void setOutsidedes(String outsidedes) {
        this.outsidedes = outsidedes;
    }

    public String getSpfinish() {
        return this.spfinish;
    }

    public void setSpfinish(String spfinish) {
        this.spfinish = spfinish;
    }

    public String getSpfinishdes() {
        return this.spfinishdes;
    }

    public void setSpfinishdes(String spfinishdes) {
        this.spfinishdes = spfinishdes;
    }

    public String getSpfinishdes2() {
        return this.spfinishdes2;
    }

    public void setSpfinishdes2(String spfinishdes2) {
        this.spfinishdes2 = spfinishdes2;
    }

    public String getEnzyme() {
        return this.enzyme;
    }

    public void setEnzyme(String enzyme) {
        this.enzyme = enzyme;
    }

    public String getEnzymedes() {
        return this.enzymedes;
    }

    public void setEnzymedes(String enzymedes) {
        this.enzymedes = enzymedes;
    }

    public String getBdsze() {
        return this.bdsze;
    }

    public void setBdsze(String bdsze) {
        this.bdsze = bdsze;
    }

    public String getStr() {
        return this.str;
    }

    public void setStr(String str) {
        this.str = str;
    }

    public String getStrdes() {
        return this.strdes;
    }

    public void setStrdes(String strdes) {
        this.strdes = strdes;
    }

    public String getStripeid() {
        return this.stripeid;
    }

    public void setStripeid(String stripeid) {
        this.stripeid = stripeid;
    }

    public String getFabcpsBsf() {
        return this.fabcpsBsf;
    }

    public void setFabcpsBsf(String fabcpsBsf) {
        this.fabcpsBsf = fabcpsBsf;
    }

    public String getFabcps() {
        return this.fabcps;
    }

    public void setFabcps(String fabcps) {
        this.fabcps = fabcps;
    }

    public String getThermobdInd() {
        return this.thermobdInd;
    }

    public void setThermobdInd(String thermobdInd) {
        this.thermobdInd = thermobdInd;
    }

    public String getLdecoroute() {
        return this.ldecoroute;
    }

    public void setLdecoroute(String ldecoroute) {
        this.ldecoroute = ldecoroute;
    }

    public String getSdecoroute() {
        return this.sdecoroute;
    }

    public void setSdecoroute(String sdecoroute) {
        this.sdecoroute = sdecoroute;
    }

    public String getDccode() {
        return this.dccode;
    }

    public void setDccode(String dccode) {
        this.dccode = dccode;
    }

    public String getDccodeldesc() {
        return this.dccodeldesc;
    }

    public void setDccodeldesc(String dccodeldesc) {
        this.dccodeldesc = dccodeldesc;
    }

    public String getDccodelabel() {
        return this.dccodelabel;
    }

    public void setDccodelabel(String dccodelabel) {
        this.dccodelabel = dccodelabel;
    }

    public String getFabdcodelist() {
        return this.fabdcodelist;
    }

    public void setFabdcodelist(String fabdcodelist) {
        this.fabdcodelist = fabdcodelist;
    }

    public String getKnshadetypdes() {
        return this.knshadetypdes;
    }

    public void setKnshadetypdes(String knshadetypdes) {
        this.knshadetypdes = knshadetypdes;
    }

    public String getKnshadetyp() {
        return this.knshadetyp;
    }

    public void setKnshadetyp(String knshadetyp) {
        this.knshadetyp = knshadetyp;
    }

    public String getCpstypa() {
        return this.cpstypa;
    }

    public void setCpstypa(String cpstypa) {
        this.cpstypa = cpstypa;
    }

    public String getCpstypades() {
        return this.cpstypades;
    }

    public void setCpstypades(String cpstypades) {
        this.cpstypades = cpstypades;
    }

    public BigInteger getCpstypafrom() {
        return this.cpstypafrom;
    }

    public void setCpstypafrom(BigInteger cpstypafrom) {
        this.cpstypafrom = cpstypafrom;
    }

    public String getCpstypb() {
        return this.cpstypb;
    }

    public void setCpstypb(String cpstypb) {
        this.cpstypb = cpstypb;
    }

    public String getCpstypbdes() {
        return this.cpstypbdes;
    }

    public void setCpstypbdes(String cpstypbdes) {
        this.cpstypbdes = cpstypbdes;
    }

    public BigInteger getCpstypbfrom() {
        return this.cpstypbfrom;
    }

    public void setCpstypbfrom(BigInteger cpstypbfrom) {
        this.cpstypbfrom = cpstypbfrom;
    }

    public String getCpstypc() {
        return this.cpstypc;
    }

    public void setCpstypc(String cpstypc) {
        this.cpstypc = cpstypc;
    }

    public String getCpstypcdes() {
        return this.cpstypcdes;
    }

    public void setCpstypcdes(String cpstypcdes) {
        this.cpstypcdes = cpstypcdes;
    }

    public BigInteger getCpstypcfrom() {
        return this.cpstypcfrom;
    }

    public void setCpstypcfrom(BigInteger cpstypcfrom) {
        this.cpstypcfrom = cpstypcfrom;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutFabdet)) return false;
        final ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutFabdet procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet = (ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutFabdet) o;
        return Objects.equals(getOrdnum(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getOrdnum()) &&
                Objects.equals(getFabseq(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getFabseq()) &&
                Objects.equals(getFabdes(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getFabdes()) &&
                Objects.equals(getFabwgt(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getFabwgt()) &&
                Objects.equals(getBsffabwgt(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getBsffabwgt()) &&
                Objects.equals(getKmchtyp(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getKmchtyp()) &&
                Objects.equals(getMchgau(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getMchgau()) &&
                Objects.equals(getInside(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getInside()) &&
                Objects.equals(getInsidedes(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getInsidedes()) &&
                Objects.equals(getOutside(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getOutside()) &&
                Objects.equals(getOutsidedes(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getOutsidedes()) &&
                Objects.equals(getSpfinish(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getSpfinish()) &&
                Objects.equals(getSpfinishdes(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getSpfinishdes()) &&
                Objects.equals(getSpfinishdes2(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getSpfinishdes2()) &&
                Objects.equals(getEnzyme(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getEnzyme()) &&
                Objects.equals(getEnzymedes(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getEnzymedes()) &&
                Objects.equals(getBdsze(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getBdsze()) &&
                Objects.equals(getStr(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getStr()) &&
                Objects.equals(getStrdes(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getStrdes()) &&
                Objects.equals(getStripeid(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getStripeid()) &&
                Objects.equals(getFabcpsBsf(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getFabcpsBsf()) &&
                Objects.equals(getFabcps(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getFabcps()) &&
                Objects.equals(getThermobdInd(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getThermobdInd()) &&
                Objects.equals(getLdecoroute(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getLdecoroute()) &&
                Objects.equals(getSdecoroute(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getSdecoroute()) &&
                Objects.equals(getDccode(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getDccode()) &&
                Objects.equals(getDccodeldesc(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getDccodeldesc()) &&
                Objects.equals(getDccodelabel(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getDccodelabel()) &&
                Objects.equals(getFabdcodelist(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getFabdcodelist()) &&
                Objects.equals(getKnshadetypdes(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getKnshadetypdes()) &&
                Objects.equals(getKnshadetyp(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getKnshadetyp()) &&
                Objects.equals(getCpstypa(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getCpstypa()) &&
                Objects.equals(getCpstypades(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getCpstypades()) &&
                Objects.equals(getCpstypafrom(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getCpstypafrom()) &&
                Objects.equals(getCpstypb(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getCpstypb()) &&
                Objects.equals(getCpstypbdes(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getCpstypbdes()) &&
                Objects.equals(getCpstypbfrom(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getCpstypbfrom()) &&
                Objects.equals(getCpstypc(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getCpstypc()) &&
                Objects.equals(getCpstypcdes(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getCpstypcdes()) &&
                Objects.equals(getCpstypcfrom(), procTt130pk0fabdevlibGetOrderDetailsResponsePoutFabdet.getCpstypcfrom());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getFabseq(),
                getFabdes(),
                getFabwgt(),
                getBsffabwgt(),
                getKmchtyp(),
                getMchgau(),
                getInside(),
                getInsidedes(),
                getOutside(),
                getOutsidedes(),
                getSpfinish(),
                getSpfinishdes(),
                getSpfinishdes2(),
                getEnzyme(),
                getEnzymedes(),
                getBdsze(),
                getStr(),
                getStrdes(),
                getStripeid(),
                getFabcpsBsf(),
                getFabcps(),
                getThermobdInd(),
                getLdecoroute(),
                getSdecoroute(),
                getDccode(),
                getDccodeldesc(),
                getDccodelabel(),
                getFabdcodelist(),
                getKnshadetypdes(),
                getKnshadetyp(),
                getCpstypa(),
                getCpstypades(),
                getCpstypafrom(),
                getCpstypb(),
                getCpstypbdes(),
                getCpstypbfrom(),
                getCpstypc(),
                getCpstypcdes(),
                getCpstypcfrom());
    }
}