/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcKn1610pk0ExcccfGetFablibKdsResponse implements Serializable {


    @ColumnAlias("pOutmsg")
    private String poutmsg;

    public String getPoutmsg() {
        return this.poutmsg;
    }

    public void setPoutmsg(String poutmsg) {
        this.poutmsg = poutmsg;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcKn1610pk0ExcccfGetFablibKdsResponse)) return false;
        final ProcKn1610pk0ExcccfGetFablibKdsResponse procKn1610pk0excccfGetFablibKdsResponse = (ProcKn1610pk0ExcccfGetFablibKdsResponse) o;
        return Objects.equals(getPoutmsg(), procKn1610pk0excccfGetFablibKdsResponse.getPoutmsg());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutmsg());
    }
}