/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf020pk0QryClrsCompareDeltaEResponsePdeltae implements Serializable {


    @ColumnAlias("DELTAE")
    private String deltae;

    @ColumnAlias("LABL1")
    private String labl1;

    @ColumnAlias("LABA1")
    private String laba1;

    @ColumnAlias("LABB1")
    private String labb1;

    @ColumnAlias("LAB1")
    private String lab1;

    @ColumnAlias("LABL2")
    private String labl2;

    @ColumnAlias("LABA2")
    private String laba2;

    @ColumnAlias("LABB2")
    private String labb2;

    @ColumnAlias("LAB2")
    private String lab2;

    public String getDeltae() {
        return this.deltae;
    }

    public void setDeltae(String deltae) {
        this.deltae = deltae;
    }

    public String getLabl1() {
        return this.labl1;
    }

    public void setLabl1(String labl1) {
        this.labl1 = labl1;
    }

    public String getLaba1() {
        return this.laba1;
    }

    public void setLaba1(String laba1) {
        this.laba1 = laba1;
    }

    public String getLabb1() {
        return this.labb1;
    }

    public void setLabb1(String labb1) {
        this.labb1 = labb1;
    }

    public String getLab1() {
        return this.lab1;
    }

    public void setLab1(String lab1) {
        this.lab1 = lab1;
    }

    public String getLabl2() {
        return this.labl2;
    }

    public void setLabl2(String labl2) {
        this.labl2 = labl2;
    }

    public String getLaba2() {
        return this.laba2;
    }

    public void setLaba2(String laba2) {
        this.laba2 = laba2;
    }

    public String getLabb2() {
        return this.labb2;
    }

    public void setLabb2(String labb2) {
        this.labb2 = labb2;
    }

    public String getLab2() {
        return this.lab2;
    }

    public void setLab2(String lab2) {
        this.lab2 = lab2;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf020pk0QryClrsCompareDeltaEResponsePdeltae)) return false;
        final ProcRf020pk0QryClrsCompareDeltaEResponsePdeltae procRf020pk0qryClrsCompareDeltaEresponsePdeltae = (ProcRf020pk0QryClrsCompareDeltaEResponsePdeltae) o;
        return Objects.equals(getDeltae(), procRf020pk0qryClrsCompareDeltaEresponsePdeltae.getDeltae()) &&
                Objects.equals(getLabl1(), procRf020pk0qryClrsCompareDeltaEresponsePdeltae.getLabl1()) &&
                Objects.equals(getLaba1(), procRf020pk0qryClrsCompareDeltaEresponsePdeltae.getLaba1()) &&
                Objects.equals(getLabb1(), procRf020pk0qryClrsCompareDeltaEresponsePdeltae.getLabb1()) &&
                Objects.equals(getLab1(), procRf020pk0qryClrsCompareDeltaEresponsePdeltae.getLab1()) &&
                Objects.equals(getLabl2(), procRf020pk0qryClrsCompareDeltaEresponsePdeltae.getLabl2()) &&
                Objects.equals(getLaba2(), procRf020pk0qryClrsCompareDeltaEresponsePdeltae.getLaba2()) &&
                Objects.equals(getLabb2(), procRf020pk0qryClrsCompareDeltaEresponsePdeltae.getLabb2()) &&
                Objects.equals(getLab2(), procRf020pk0qryClrsCompareDeltaEresponsePdeltae.getLab2());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDeltae(),
                getLabl1(),
                getLaba1(),
                getLabb1(),
                getLab1(),
                getLabl2(),
                getLaba2(),
                getLabb2(),
                getLab2());
    }
}