/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcKn1610pk0ExcccfGetOrderStsResponse implements Serializable {


    @ColumnAlias("p_outDesc")
    private String poutDesc;

    @ColumnAlias("p_tcf_allowed")
    private String ptcfAllowed;

    @ColumnAlias("p_ccf_allowed")
    private String pccfAllowed;

    @ColumnAlias("p_cancel_allowed")
    private String pcancelAllowed;

    @ColumnAlias("p_intfabcertrem")
    private String pintfabcertrem;

    public String getPoutDesc() {
        return this.poutDesc;
    }

    public void setPoutDesc(String poutDesc) {
        this.poutDesc = poutDesc;
    }

    public String getPtcfAllowed() {
        return this.ptcfAllowed;
    }

    public void setPtcfAllowed(String ptcfAllowed) {
        this.ptcfAllowed = ptcfAllowed;
    }

    public String getPccfAllowed() {
        return this.pccfAllowed;
    }

    public void setPccfAllowed(String pccfAllowed) {
        this.pccfAllowed = pccfAllowed;
    }

    public String getPcancelAllowed() {
        return this.pcancelAllowed;
    }

    public void setPcancelAllowed(String pcancelAllowed) {
        this.pcancelAllowed = pcancelAllowed;
    }

    public String getPintfabcertrem() {
        return this.pintfabcertrem;
    }

    public void setPintfabcertrem(String pintfabcertrem) {
        this.pintfabcertrem = pintfabcertrem;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcKn1610pk0ExcccfGetOrderStsResponse)) return false;
        final ProcKn1610pk0ExcccfGetOrderStsResponse procKn1610pk0excccfGetOrderStsResponse = (ProcKn1610pk0ExcccfGetOrderStsResponse) o;
        return Objects.equals(getPoutDesc(), procKn1610pk0excccfGetOrderStsResponse.getPoutDesc()) &&
                Objects.equals(getPtcfAllowed(), procKn1610pk0excccfGetOrderStsResponse.getPtcfAllowed()) &&
                Objects.equals(getPccfAllowed(), procKn1610pk0excccfGetOrderStsResponse.getPccfAllowed()) &&
                Objects.equals(getPcancelAllowed(), procKn1610pk0excccfGetOrderStsResponse.getPcancelAllowed()) &&
                Objects.equals(getPintfabcertrem(), procKn1610pk0excccfGetOrderStsResponse.getPintfabcertrem());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutDesc(),
                getPtcfAllowed(),
                getPccfAllowed(),
                getPcancelAllowed(),
                getPintfabcertrem());
    }
}