/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcTt130pk0FabdevlibGetOrderDetailsResponse implements Serializable {


    @ColumnAlias("p_out_fabdet")
    private List<ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutFabdet> poutFabdet;

    @ColumnAlias("p_out_yarndet")
    private List<ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutYarndet> poutYarndet;

    public List<ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutFabdet> getPoutFabdet() {
        return this.poutFabdet;
    }

    public void setPoutFabdet(List<ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutFabdet> poutFabdet) {
        this.poutFabdet = poutFabdet;
    }

    public List<ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutYarndet> getPoutYarndet() {
        return this.poutYarndet;
    }

    public void setPoutYarndet(List<ProcTt130pk0FabdevlibGetOrderDetailsResponsePoutYarndet> poutYarndet) {
        this.poutYarndet = poutYarndet;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcTt130pk0FabdevlibGetOrderDetailsResponse)) return false;
        final ProcTt130pk0FabdevlibGetOrderDetailsResponse procTt130pk0fabdevlibGetOrderDetailsResponse = (ProcTt130pk0FabdevlibGetOrderDetailsResponse) o;
        return Objects.equals(getPoutFabdet(), procTt130pk0fabdevlibGetOrderDetailsResponse.getPoutFabdet()) &&
                Objects.equals(getPoutYarndet(), procTt130pk0fabdevlibGetOrderDetailsResponse.getPoutYarndet());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutFabdet(),
                getPoutYarndet());
    }
}