/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcKn1620pk0ccfmQryGetMatchDetResponse implements Serializable {


    @ColumnAlias("pOutMatchDet")
    private List<ProcKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet> poutMatchDet;

    public List<ProcKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet> getPoutMatchDet() {
        return this.poutMatchDet;
    }

    public void setPoutMatchDet(List<ProcKn1620pk0ccfmQryGetMatchDetResponsePoutMatchDet> poutMatchDet) {
        this.poutMatchDet = poutMatchDet;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcKn1620pk0ccfmQryGetMatchDetResponse)) return false;
        final ProcKn1620pk0ccfmQryGetMatchDetResponse procKn1620pk0ccfmQryGetMatchDetResponse = (ProcKn1620pk0ccfmQryGetMatchDetResponse) o;
        return Objects.equals(getPoutMatchDet(), procKn1620pk0ccfmQryGetMatchDetResponse.getPoutMatchDet());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutMatchDet());
    }
}