/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf020pk0UpdClrsAddPantoneResponse implements Serializable {


    @ColumnAlias("p_outDetails")
    private List<ProcRf020pk0UpdClrsAddPantoneResponsePoutDetails> poutDetails;

    public List<ProcRf020pk0UpdClrsAddPantoneResponsePoutDetails> getPoutDetails() {
        return this.poutDetails;
    }

    public void setPoutDetails(List<ProcRf020pk0UpdClrsAddPantoneResponsePoutDetails> poutDetails) {
        this.poutDetails = poutDetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf020pk0UpdClrsAddPantoneResponse)) return false;
        final ProcRf020pk0UpdClrsAddPantoneResponse procRf020pk0updClrsAddPantoneResponse = (ProcRf020pk0UpdClrsAddPantoneResponse) o;
        return Objects.equals(getPoutDetails(), procRf020pk0updClrsAddPantoneResponse.getPoutDetails());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutDetails());
    }
}