/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf020pk0getClrOptResponsePoutLov implements Serializable {


    @ColumnAlias("CLRCODE")
    private String clrcode;

    @ColumnAlias("RGBR")
    private Short rgbr;

    @ColumnAlias("RGBG")
    private Short rgbg;

    @ColumnAlias("RGBB")
    private Short rgbb;

    @ColumnAlias("LABL")
    private Float labl;

    @ColumnAlias("LABA")
    private Float laba;

    @ColumnAlias("LABB")
    private Float labb;

    public String getClrcode() {
        return this.clrcode;
    }

    public void setClrcode(String clrcode) {
        this.clrcode = clrcode;
    }

    public Short getRgbr() {
        return this.rgbr;
    }

    public void setRgbr(Short rgbr) {
        this.rgbr = rgbr;
    }

    public Short getRgbg() {
        return this.rgbg;
    }

    public void setRgbg(Short rgbg) {
        this.rgbg = rgbg;
    }

    public Short getRgbb() {
        return this.rgbb;
    }

    public void setRgbb(Short rgbb) {
        this.rgbb = rgbb;
    }

    public Float getLabl() {
        return this.labl;
    }

    public void setLabl(Float labl) {
        this.labl = labl;
    }

    public Float getLaba() {
        return this.laba;
    }

    public void setLaba(Float laba) {
        this.laba = laba;
    }

    public Float getLabb() {
        return this.labb;
    }

    public void setLabb(Float labb) {
        this.labb = labb;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf020pk0getClrOptResponsePoutLov)) return false;
        final ProcRf020pk0getClrOptResponsePoutLov procRf020pk0getClrOptResponsePoutLov = (ProcRf020pk0getClrOptResponsePoutLov) o;
        return Objects.equals(getClrcode(), procRf020pk0getClrOptResponsePoutLov.getClrcode()) &&
                Objects.equals(getRgbr(), procRf020pk0getClrOptResponsePoutLov.getRgbr()) &&
                Objects.equals(getRgbg(), procRf020pk0getClrOptResponsePoutLov.getRgbg()) &&
                Objects.equals(getRgbb(), procRf020pk0getClrOptResponsePoutLov.getRgbb()) &&
                Objects.equals(getLabl(), procRf020pk0getClrOptResponsePoutLov.getLabl()) &&
                Objects.equals(getLaba(), procRf020pk0getClrOptResponsePoutLov.getLaba()) &&
                Objects.equals(getLabb(), procRf020pk0getClrOptResponsePoutLov.getLabb());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getClrcode(),
                getRgbr(),
                getRgbg(),
                getRgbb(),
                getLabl(),
                getLaba(),
                getLabb());
    }
}