/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SprocMatchFabricClrResponsePfabrics implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("CLICOD")
    private String clicod;

    @ColumnAlias("FABTYP")
    private String fabtyp;

    @ColumnAlias("FABWGT")
    private Short fabwgt;

    @ColumnAlias("FABWID")
    private BigInteger fabwid;

    @ColumnAlias("CLRDES")
    private String clrdes;

    @ColumnAlias("LAB")
    private String lab;

    @ColumnAlias("DELTAE")
    private String deltae;

    @ColumnAlias("MCHGAU")
    private BigInteger mchgau;

    @ColumnAlias("CLRREF")
    private String clrref;

    @ColumnAlias("STRIPEID")
    private String stripeid;

    @ColumnAlias("FABDCODELIST")
    private String fabdcodelist;

    @ColumnAlias("INSIDE")
    private String inside;

    @ColumnAlias("OUTSIDE")
    private String outside;

    @ColumnAlias("SPFINISH")
    private String spfinish;

    @ColumnAlias("ENZYMEWASH")
    private String enzymewash;

    @ColumnAlias("SKUNO")
    private String skuno;

    @ColumnAlias("CALSTN")
    private String calstn;

    @ColumnAlias("SDECOROUTE")
    private String sdecoroute;

    @ColumnAlias("LDECOROUTE")
    private String ldecoroute;

    @ColumnAlias("YRNID")
    private BigInteger yrnid;

    @ColumnAlias("FABIMAGEREF")
    private String fabimageref;

    @ColumnAlias("STOCK")
    private String stock;

    @ColumnAlias("STORELOC")
    private String storeloc;

    @ColumnAlias("STRCOD")
    private String strcod;

    @ColumnAlias("FABCOMPO")
    private String fabcompo;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("CLRSEQ")
    private Byte clrseq;

    @ColumnAlias("CCFDET")
    private String ccfdet;

    @ColumnAlias("SIMILARCCFDET")
    private String similarccfdet;

    @ColumnAlias("STOCKSRC")
    private String stocksrc;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    public String getFabtyp() {
        return this.fabtyp;
    }

    public void setFabtyp(String fabtyp) {
        this.fabtyp = fabtyp;
    }

    public Short getFabwgt() {
        return this.fabwgt;
    }

    public void setFabwgt(Short fabwgt) {
        this.fabwgt = fabwgt;
    }

    public BigInteger getFabwid() {
        return this.fabwid;
    }

    public void setFabwid(BigInteger fabwid) {
        this.fabwid = fabwid;
    }

    public String getClrdes() {
        return this.clrdes;
    }

    public void setClrdes(String clrdes) {
        this.clrdes = clrdes;
    }

    public String getLab() {
        return this.lab;
    }

    public void setLab(String lab) {
        this.lab = lab;
    }

    public String getDeltae() {
        return this.deltae;
    }

    public void setDeltae(String deltae) {
        this.deltae = deltae;
    }

    public BigInteger getMchgau() {
        return this.mchgau;
    }

    public void setMchgau(BigInteger mchgau) {
        this.mchgau = mchgau;
    }

    public String getClrref() {
        return this.clrref;
    }

    public void setClrref(String clrref) {
        this.clrref = clrref;
    }

    public String getStripeid() {
        return this.stripeid;
    }

    public void setStripeid(String stripeid) {
        this.stripeid = stripeid;
    }

    public String getFabdcodelist() {
        return this.fabdcodelist;
    }

    public void setFabdcodelist(String fabdcodelist) {
        this.fabdcodelist = fabdcodelist;
    }

    public String getInside() {
        return this.inside;
    }

    public void setInside(String inside) {
        this.inside = inside;
    }

    public String getOutside() {
        return this.outside;
    }

    public void setOutside(String outside) {
        this.outside = outside;
    }

    public String getSpfinish() {
        return this.spfinish;
    }

    public void setSpfinish(String spfinish) {
        this.spfinish = spfinish;
    }

    public String getEnzymewash() {
        return this.enzymewash;
    }

    public void setEnzymewash(String enzymewash) {
        this.enzymewash = enzymewash;
    }

    public String getSkuno() {
        return this.skuno;
    }

    public void setSkuno(String skuno) {
        this.skuno = skuno;
    }

    public String getCalstn() {
        return this.calstn;
    }

    public void setCalstn(String calstn) {
        this.calstn = calstn;
    }

    public String getSdecoroute() {
        return this.sdecoroute;
    }

    public void setSdecoroute(String sdecoroute) {
        this.sdecoroute = sdecoroute;
    }

    public String getLdecoroute() {
        return this.ldecoroute;
    }

    public void setLdecoroute(String ldecoroute) {
        this.ldecoroute = ldecoroute;
    }

    public BigInteger getYrnid() {
        return this.yrnid;
    }

    public void setYrnid(BigInteger yrnid) {
        this.yrnid = yrnid;
    }

    public String getFabimageref() {
        return this.fabimageref;
    }

    public void setFabimageref(String fabimageref) {
        this.fabimageref = fabimageref;
    }

    public String getStock() {
        return this.stock;
    }

    public void setStock(String stock) {
        this.stock = stock;
    }

    public String getStoreloc() {
        return this.storeloc;
    }

    public void setStoreloc(String storeloc) {
        this.storeloc = storeloc;
    }

    public String getStrcod() {
        return this.strcod;
    }

    public void setStrcod(String strcod) {
        this.strcod = strcod;
    }

    public String getFabcompo() {
        return this.fabcompo;
    }

    public void setFabcompo(String fabcompo) {
        this.fabcompo = fabcompo;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public Byte getClrseq() {
        return this.clrseq;
    }

    public void setClrseq(Byte clrseq) {
        this.clrseq = clrseq;
    }

    public String getCcfdet() {
        return this.ccfdet;
    }

    public void setCcfdet(String ccfdet) {
        this.ccfdet = ccfdet;
    }

    public String getSimilarccfdet() {
        return this.similarccfdet;
    }

    public void setSimilarccfdet(String similarccfdet) {
        this.similarccfdet = similarccfdet;
    }

    public String getStocksrc() {
        return this.stocksrc;
    }

    public void setStocksrc(String stocksrc) {
        this.stocksrc = stocksrc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SprocMatchFabricClrResponsePfabrics)) return false;
        final SprocMatchFabricClrResponsePfabrics sprocMatchFabricClrResponsePfabrics = (SprocMatchFabricClrResponsePfabrics) o;
        return Objects.equals(getOrdnum(), sprocMatchFabricClrResponsePfabrics.getOrdnum()) &&
                Objects.equals(getClicod(), sprocMatchFabricClrResponsePfabrics.getClicod()) &&
                Objects.equals(getFabtyp(), sprocMatchFabricClrResponsePfabrics.getFabtyp()) &&
                Objects.equals(getFabwgt(), sprocMatchFabricClrResponsePfabrics.getFabwgt()) &&
                Objects.equals(getFabwid(), sprocMatchFabricClrResponsePfabrics.getFabwid()) &&
                Objects.equals(getClrdes(), sprocMatchFabricClrResponsePfabrics.getClrdes()) &&
                Objects.equals(getLab(), sprocMatchFabricClrResponsePfabrics.getLab()) &&
                Objects.equals(getDeltae(), sprocMatchFabricClrResponsePfabrics.getDeltae()) &&
                Objects.equals(getMchgau(), sprocMatchFabricClrResponsePfabrics.getMchgau()) &&
                Objects.equals(getClrref(), sprocMatchFabricClrResponsePfabrics.getClrref()) &&
                Objects.equals(getStripeid(), sprocMatchFabricClrResponsePfabrics.getStripeid()) &&
                Objects.equals(getFabdcodelist(), sprocMatchFabricClrResponsePfabrics.getFabdcodelist()) &&
                Objects.equals(getInside(), sprocMatchFabricClrResponsePfabrics.getInside()) &&
                Objects.equals(getOutside(), sprocMatchFabricClrResponsePfabrics.getOutside()) &&
                Objects.equals(getSpfinish(), sprocMatchFabricClrResponsePfabrics.getSpfinish()) &&
                Objects.equals(getEnzymewash(), sprocMatchFabricClrResponsePfabrics.getEnzymewash()) &&
                Objects.equals(getSkuno(), sprocMatchFabricClrResponsePfabrics.getSkuno()) &&
                Objects.equals(getCalstn(), sprocMatchFabricClrResponsePfabrics.getCalstn()) &&
                Objects.equals(getSdecoroute(), sprocMatchFabricClrResponsePfabrics.getSdecoroute()) &&
                Objects.equals(getLdecoroute(), sprocMatchFabricClrResponsePfabrics.getLdecoroute()) &&
                Objects.equals(getYrnid(), sprocMatchFabricClrResponsePfabrics.getYrnid()) &&
                Objects.equals(getFabimageref(), sprocMatchFabricClrResponsePfabrics.getFabimageref()) &&
                Objects.equals(getStock(), sprocMatchFabricClrResponsePfabrics.getStock()) &&
                Objects.equals(getStoreloc(), sprocMatchFabricClrResponsePfabrics.getStoreloc()) &&
                Objects.equals(getStrcod(), sprocMatchFabricClrResponsePfabrics.getStrcod()) &&
                Objects.equals(getFabcompo(), sprocMatchFabricClrResponsePfabrics.getFabcompo()) &&
                Objects.equals(getFabseq(), sprocMatchFabricClrResponsePfabrics.getFabseq()) &&
                Objects.equals(getClrseq(), sprocMatchFabricClrResponsePfabrics.getClrseq()) &&
                Objects.equals(getCcfdet(), sprocMatchFabricClrResponsePfabrics.getCcfdet()) &&
                Objects.equals(getSimilarccfdet(), sprocMatchFabricClrResponsePfabrics.getSimilarccfdet()) &&
                Objects.equals(getStocksrc(), sprocMatchFabricClrResponsePfabrics.getStocksrc());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getClicod(),
                getFabtyp(),
                getFabwgt(),
                getFabwid(),
                getClrdes(),
                getLab(),
                getDeltae(),
                getMchgau(),
                getClrref(),
                getStripeid(),
                getFabdcodelist(),
                getInside(),
                getOutside(),
                getSpfinish(),
                getEnzymewash(),
                getSkuno(),
                getCalstn(),
                getSdecoroute(),
                getLdecoroute(),
                getYrnid(),
                getFabimageref(),
                getStock(),
                getStoreloc(),
                getStrcod(),
                getFabcompo(),
                getFabseq(),
                getClrseq(),
                getCcfdet(),
                getSimilarccfdet(),
                getStocksrc());
    }
}