/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SprocMatchFabricClrResponse implements Serializable {


    @ColumnAlias("pFabrics")
    private List<SprocMatchFabricClrResponsePfabrics> pfabrics;

    public List<SprocMatchFabricClrResponsePfabrics> getPfabrics() {
        return this.pfabrics;
    }

    public void setPfabrics(List<SprocMatchFabricClrResponsePfabrics> pfabrics) {
        this.pfabrics = pfabrics;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SprocMatchFabricClrResponse)) return false;
        final SprocMatchFabricClrResponse sprocMatchFabricClrResponse = (SprocMatchFabricClrResponse) o;
        return Objects.equals(getPfabrics(), sprocMatchFabricClrResponse.getPfabrics());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPfabrics());
    }
}