/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateTt130pk0FabdevlibRequestFabSrcMailRequest implements Serializable {


    @JsonProperty("pStrFrmWM")
    private String pstrFrmWm;

    @JsonProperty("pYarnFilter")
    private String pyarnFilter;

    @JsonProperty("pRemakrs")
    private String premakrs;

    @JsonProperty("pClient")
    private String pclient;

    public String getPstrFrmWm() {
        return this.pstrFrmWm;
    }

    public void setPstrFrmWm(String pstrFrmWm) {
        this.pstrFrmWm = pstrFrmWm;
    }

    public String getPyarnFilter() {
        return this.pyarnFilter;
    }

    public void setPyarnFilter(String pyarnFilter) {
        this.pyarnFilter = pyarnFilter;
    }

    public String getPremakrs() {
        return this.premakrs;
    }

    public void setPremakrs(String premakrs) {
        this.premakrs = premakrs;
    }

    public String getPclient() {
        return this.pclient;
    }

    public void setPclient(String pclient) {
        this.pclient = pclient;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateTt130pk0FabdevlibRequestFabSrcMailRequest)) return false;
        final UpdateTt130pk0FabdevlibRequestFabSrcMailRequest updateTt130pk0fabdevlibRequestFabSrcMailRequest = (UpdateTt130pk0FabdevlibRequestFabSrcMailRequest) o;
        return Objects.equals(getPstrFrmWm(), updateTt130pk0fabdevlibRequestFabSrcMailRequest.getPstrFrmWm()) &&
                Objects.equals(getPyarnFilter(), updateTt130pk0fabdevlibRequestFabSrcMailRequest.getPyarnFilter()) &&
                Objects.equals(getPremakrs(), updateTt130pk0fabdevlibRequestFabSrcMailRequest.getPremakrs()) &&
                Objects.equals(getPclient(), updateTt130pk0fabdevlibRequestFabSrcMailRequest.getPclient());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPstrFrmWm(),
                getPyarnFilter(),
                getPremakrs(),
                getPclient());
    }
}