/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Ort120 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ORT120`")
@IdClass(Ort120Id.class)
public class Ort120 implements Serializable {

    private String ordnum;
    private Byte fabseq;
    private LocalDateTime ekntdat;
    private LocalDateTime edyedat;
    private String fabtyp;
    private Short fabwgt;
    private Short gfabwgt;
    private Float fabwid;
    private String kmchtyp;
    private Short mchgau;
    private Short mchwid;
    private Double amtreq;
    private Double wgtreq;
    private String trimsr;
    private String kntsts;
    private String calstn;
    private String fabind;
    private String allind;
    private Float fabrto;
    private String brush;
    private String emerise;
    private String inside;
    private String outside;
    private String teflon;
    private String enzyme;
    private Byte optseq;
    private String str;
    private Float trimpwgt;
    private String knreq;
    private String fdreq;
    private String bdsze;
    private String usrid;
    private LocalDateTime usrdate;
    private Short bsffabwgt;
    private String cuuom;
    private Double uinirto;
    private String urtotyp;
    private Float kinirto;
    private Double cuamtreq;
    private Double cukgsreq;
    private String amtuom;
    private Float trimhgt;
    private Float trimwid;
    private String patcod;
    private String knshade;
    private String recalcopt;
    private Double dystkamt;
    private String dystkuom;
    private Double dyamtreq;
    private Double dykgsreq;
    private String dyuom;
    private String templateseq;
    private Byte kntfabseq;
    private String selfbd;
    private String bathdye;
    private String contdye;
    private String potdye;
    private Float bestfabwid;
    private String newtrimsr;
    private String cmbflag;
    private String recalctrim;
    private String fabsubcat;
    private String stripeid;
    private Byte faborien;
    private String aloprtid;
    private String aloprtlcn;
    private Short alopvar;
    private String cutstr;
    private String designer;
    private String recalcclrper;
    private String skuno;
    private String notdye;
    private String oldfabtyp;
    private String oldskuno;
    private Float nwasteAop;
    private String fabsts = "'PLN'";
    private String fstsid;
    private LocalDateTime fstsdate;
    private String fstsreascod;
    private String relstg;
    private String srcOrdnum;
    private Byte srcFabseq;
    private String srcIntrefno;
    private Short srcIntrefnoVer;
    private Short srcTemplateseqVer;
    private Short srcTemplateseqYrnopt;
    private Short srcTemplateseqYrnoptVer;
    private String recalcNwasteAop;
    private String trimsrDimdes;
    private Float trimlen;
    private Float selvwdth;
    private String heatsetreq;
    private Float residualwdth;
    private String opencompactreq;
    private Float cutspreadwdthPercentDiff;
    private Float cutborderwdth;
    private String lotno;
    private Short lotseq;
    private String dyetestreq;
    private Byte dyetestseq;
    private String animonfab;
    private String dsgreqProposaloption;
    private LocalDateTime dsgreqModdat;
    private String dsgreqModby;
    private String faceside;
    private String markertyp;
    private String basehangerSrcrefreq;
    private String basehangerSrcrefordnum;
    private Byte basehangerSrcreffabseq;
    private Double uinirtoIndicative;
    private Float kinirtoIndicative;
    private String inirtoIndicativeReason;
    private Byte skewangle;
    private Float stephgt;
    private Double skewwaste;
    private Float bodylen;
    private Float tightness;
    private String fabcpsBsf;
    private String fabcps;
    private String fabcpsClient;
    private String fabcpsRecalc;
    private Byte cmbfabseq;
    private String thermobdInd;
    private String fabdcodelist;
    private String ldecoroute;
    private String sdecoroute;
    private String dccode;
    private Byte cmbfablayer;
    private String methodseq;
    private Short skumatseq;
    private String dyemethodcod;
    private String skumatrixid;
    private String dyectycod;
    private String usablewidFaboptrecalc;
    private Float usablewidAdyefn;
    private Float usablewidAskew;
    private Float usablewidAmlf;
    private String matnotdye;
    private Float knrbp;
    private String kndyetyp;
    private String drdyetyp;
    private Byte cmbtargfabseq;
    private String techcode;
    private Short techvar;
    private String techplacement;
    private String aopstrikeoff;
    private String aopstrikeoffby;
    private LocalDateTime aopstrikeoffdate;
    private String ydcalcPrevsts;
    private String ydcalcPrevstsby;
    private LocalDateTime ydcalcPrevstsdate;
    private String ydcalcSts;
    private String ydcalcStsby;
    private LocalDateTime ydcalcStsdate;
    private Float ydcalcRepeat;
    private Float ydcalcFullfeed;
    private String patfabtyp;
    private String fabdetRecalc;
    private String srcFabmodind;
    private String kntctycod;
    private String fabbaseno;
    private String dccodeRecalc;
    private String fabbaseyrnRecalc;
    private String fabbaseDevind;
    private String basehangerSrcnotreq;
    private String basehangerSrcreqindModid;
    private LocalDateTime basehangerSrcreqindModdat;
    private String basehangerSrcrefapvind;
    private String aopstrikeoffRequired;
    private String aopstrikeoffNotrequired;
    private String aopstrikeoffAopcode;
    private Short aopstrikeoffAopvar;
    private String aopstrikeoffModby;
    private LocalDateTime aopstrikeoffModdate;
    private String aopstrikeoffSrcrefordnum;
    private Byte aopstrikeoffSrcreffabseq;
    private String aopstrikeoffApvind;
    private String intfabcertno;
    private String intfabcertnoFixedind;

    @Id
    @Column(name = "`ORDNUM`", nullable = false, length = 12)
    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    @Id
    @Column(name = "`FABSEQ`", nullable = false, scale = 0, precision = 2)
    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    @Column(name = "`EKNTDAT`", nullable = true)
    public LocalDateTime getEkntdat() {
        return this.ekntdat;
    }

    public void setEkntdat(LocalDateTime ekntdat) {
        this.ekntdat = ekntdat;
    }

    @Column(name = "`EDYEDAT`", nullable = true)
    public LocalDateTime getEdyedat() {
        return this.edyedat;
    }

    public void setEdyedat(LocalDateTime edyedat) {
        this.edyedat = edyedat;
    }

    @Column(name = "`FABTYP`", nullable = false, length = 7)
    public String getFabtyp() {
        return this.fabtyp;
    }

    public void setFabtyp(String fabtyp) {
        this.fabtyp = fabtyp;
    }

    @Column(name = "`FABWGT`", nullable = true, scale = 0, precision = 3)
    public Short getFabwgt() {
        return this.fabwgt;
    }

    public void setFabwgt(Short fabwgt) {
        this.fabwgt = fabwgt;
    }

    @Column(name = "`GFABWGT`", nullable = true, scale = 0, precision = 3)
    public Short getGfabwgt() {
        return this.gfabwgt;
    }

    public void setGfabwgt(Short gfabwgt) {
        this.gfabwgt = gfabwgt;
    }

    @Column(name = "`FABWID`", nullable = true, scale = 1, precision = 4)
    public Float getFabwid() {
        return this.fabwid;
    }

    public void setFabwid(Float fabwid) {
        this.fabwid = fabwid;
    }

    @Column(name = "`KMCHTYP`", nullable = true, length = 4)
    public String getKmchtyp() {
        return this.kmchtyp;
    }

    public void setKmchtyp(String kmchtyp) {
        this.kmchtyp = kmchtyp;
    }

    @Column(name = "`MCHGAU`", nullable = true, scale = 0, precision = 3)
    public Short getMchgau() {
        return this.mchgau;
    }

    public void setMchgau(Short mchgau) {
        this.mchgau = mchgau;
    }

    @Column(name = "`MCHWID`", nullable = true, scale = 0, precision = 3)
    public Short getMchwid() {
        return this.mchwid;
    }

    public void setMchwid(Short mchwid) {
        this.mchwid = mchwid;
    }

    @Column(name = "`AMTREQ`", nullable = true, scale = 2, precision = 8)
    public Double getAmtreq() {
        return this.amtreq;
    }

    public void setAmtreq(Double amtreq) {
        this.amtreq = amtreq;
    }

    @Column(name = "`WGTREQ`", nullable = true, scale = 2, precision = 8)
    public Double getWgtreq() {
        return this.wgtreq;
    }

    public void setWgtreq(Double wgtreq) {
        this.wgtreq = wgtreq;
    }

    @Column(name = "`TRIMSR`", nullable = true, length = 10)
    public String getTrimsr() {
        return this.trimsr;
    }

    public void setTrimsr(String trimsr) {
        this.trimsr = trimsr;
    }

    @Column(name = "`KNTSTS`", nullable = true, length = 1)
    public String getKntsts() {
        return this.kntsts;
    }

    public void setKntsts(String kntsts) {
        this.kntsts = kntsts;
    }

    @Column(name = "`CALSTN`", nullable = true, length = 1)
    public String getCalstn() {
        return this.calstn;
    }

    public void setCalstn(String calstn) {
        this.calstn = calstn;
    }

    @Column(name = "`FABIND`", nullable = true, length = 1)
    public String getFabind() {
        return this.fabind;
    }

    public void setFabind(String fabind) {
        this.fabind = fabind;
    }

    @Column(name = "`ALLIND`", nullable = true, length = 1)
    public String getAllind() {
        return this.allind;
    }

    public void setAllind(String allind) {
        this.allind = allind;
    }

    @Column(name = "`FABRTO`", nullable = true, scale = 2, precision = 6)
    public Float getFabrto() {
        return this.fabrto;
    }

    public void setFabrto(Float fabrto) {
        this.fabrto = fabrto;
    }

    @Column(name = "`BRUSH`", nullable = true, length = 1)
    public String getBrush() {
        return this.brush;
    }

    public void setBrush(String brush) {
        this.brush = brush;
    }

    @Column(name = "`EMERISE`", nullable = true, length = 1)
    public String getEmerise() {
        return this.emerise;
    }

    public void setEmerise(String emerise) {
        this.emerise = emerise;
    }

    @Column(name = "`INSIDE`", nullable = true, length = 2)
    public String getInside() {
        return this.inside;
    }

    public void setInside(String inside) {
        this.inside = inside;
    }

    @Column(name = "`OUTSIDE`", nullable = true, length = 2)
    public String getOutside() {
        return this.outside;
    }

    public void setOutside(String outside) {
        this.outside = outside;
    }

    @Column(name = "`TEFLON`", nullable = true, length = 2)
    public String getTeflon() {
        return this.teflon;
    }

    public void setTeflon(String teflon) {
        this.teflon = teflon;
    }

    @Column(name = "`ENZYME`", nullable = true, length = 2)
    public String getEnzyme() {
        return this.enzyme;
    }

    public void setEnzyme(String enzyme) {
        this.enzyme = enzyme;
    }

    @Column(name = "`OPTSEQ`", nullable = true, scale = 0, precision = 2)
    public Byte getOptseq() {
        return this.optseq;
    }

    public void setOptseq(Byte optseq) {
        this.optseq = optseq;
    }

    @Column(name = "`STR`", nullable = true, length = 1)
    public String getStr() {
        return this.str;
    }

    public void setStr(String str) {
        this.str = str;
    }

    @Column(name = "`TRIMPWGT`", nullable = true, scale = 3, precision = 6)
    public Float getTrimpwgt() {
        return this.trimpwgt;
    }

    public void setTrimpwgt(Float trimpwgt) {
        this.trimpwgt = trimpwgt;
    }

    @Column(name = "`KNREQ`", nullable = true, length = 1)
    public String getKnreq() {
        return this.knreq;
    }

    public void setKnreq(String knreq) {
        this.knreq = knreq;
    }

    @Column(name = "`FDREQ`", nullable = true, length = 1)
    public String getFdreq() {
        return this.fdreq;
    }

    public void setFdreq(String fdreq) {
        this.fdreq = fdreq;
    }

    @Column(name = "`BDSZE`", nullable = true, length = 1)
    public String getBdsze() {
        return this.bdsze;
    }

    public void setBdsze(String bdsze) {
        this.bdsze = bdsze;
    }

    @Column(name = "`USRID`", nullable = true, length = 6)
    public String getUsrid() {
        return this.usrid;
    }

    public void setUsrid(String usrid) {
        this.usrid = usrid;
    }

    @Column(name = "`USRDATE`", nullable = true)
    public LocalDateTime getUsrdate() {
        return this.usrdate;
    }

    public void setUsrdate(LocalDateTime usrdate) {
        this.usrdate = usrdate;
    }

    @Column(name = "`BSFFABWGT`", nullable = true, scale = 0, precision = 3)
    public Short getBsffabwgt() {
        return this.bsffabwgt;
    }

    public void setBsffabwgt(Short bsffabwgt) {
        this.bsffabwgt = bsffabwgt;
    }

    @Column(name = "`CUUOM`", nullable = true, length = 3)
    public String getCuuom() {
        return this.cuuom;
    }

    public void setCuuom(String cuuom) {
        this.cuuom = cuuom;
    }

    @Column(name = "`UINIRTO`", nullable = true, scale = 4, precision = 8)
    public Double getUinirto() {
        return this.uinirto;
    }

    public void setUinirto(Double uinirto) {
        this.uinirto = uinirto;
    }

    @Column(name = "`URTOTYP`", nullable = true, length = 1)
    public String getUrtotyp() {
        return this.urtotyp;
    }

    public void setUrtotyp(String urtotyp) {
        this.urtotyp = urtotyp;
    }

    @Column(name = "`KINIRTO`", nullable = true, scale = 3, precision = 7)
    public Float getKinirto() {
        return this.kinirto;
    }

    public void setKinirto(Float kinirto) {
        this.kinirto = kinirto;
    }

    @Column(name = "`CUAMTREQ`", nullable = true, scale = 2, precision = 8)
    public Double getCuamtreq() {
        return this.cuamtreq;
    }

    public void setCuamtreq(Double cuamtreq) {
        this.cuamtreq = cuamtreq;
    }

    @Column(name = "`CUKGSREQ`", nullable = true, scale = 2, precision = 8)
    public Double getCukgsreq() {
        return this.cukgsreq;
    }

    public void setCukgsreq(Double cukgsreq) {
        this.cukgsreq = cukgsreq;
    }

    @Column(name = "`AMTUOM`", nullable = true, length = 3)
    public String getAmtuom() {
        return this.amtuom;
    }

    public void setAmtuom(String amtuom) {
        this.amtuom = amtuom;
    }

    @Column(name = "`TRIMHGT`", nullable = true, scale = 2, precision = 5)
    public Float getTrimhgt() {
        return this.trimhgt;
    }

    public void setTrimhgt(Float trimhgt) {
        this.trimhgt = trimhgt;
    }

    @Column(name = "`TRIMWID`", nullable = true, scale = 2, precision = 5)
    public Float getTrimwid() {
        return this.trimwid;
    }

    public void setTrimwid(Float trimwid) {
        this.trimwid = trimwid;
    }

    @Column(name = "`PATCOD`", nullable = true, length = 15)
    public String getPatcod() {
        return this.patcod;
    }

    public void setPatcod(String patcod) {
        this.patcod = patcod;
    }

    @Column(name = "`KNSHADE`", nullable = true, length = 14)
    public String getKnshade() {
        return this.knshade;
    }

    public void setKnshade(String knshade) {
        this.knshade = knshade;
    }

    @Column(name = "`RECALCOPT`", nullable = true, length = 1)
    public String getRecalcopt() {
        return this.recalcopt;
    }

    public void setRecalcopt(String recalcopt) {
        this.recalcopt = recalcopt;
    }

    @Column(name = "`DYSTKAMT`", nullable = true, scale = 2, precision = 8)
    public Double getDystkamt() {
        return this.dystkamt;
    }

    public void setDystkamt(Double dystkamt) {
        this.dystkamt = dystkamt;
    }

    @Column(name = "`DYSTKUOM`", nullable = true, length = 3)
    public String getDystkuom() {
        return this.dystkuom;
    }

    public void setDystkuom(String dystkuom) {
        this.dystkuom = dystkuom;
    }

    @Column(name = "`DYAMTREQ`", nullable = true, scale = 2, precision = 8)
    public Double getDyamtreq() {
        return this.dyamtreq;
    }

    public void setDyamtreq(Double dyamtreq) {
        this.dyamtreq = dyamtreq;
    }

    @Column(name = "`DYKGSREQ`", nullable = true, scale = 2, precision = 8)
    public Double getDykgsreq() {
        return this.dykgsreq;
    }

    public void setDykgsreq(Double dykgsreq) {
        this.dykgsreq = dykgsreq;
    }

    @Column(name = "`DYUOM`", nullable = true, length = 3)
    public String getDyuom() {
        return this.dyuom;
    }

    public void setDyuom(String dyuom) {
        this.dyuom = dyuom;
    }

    @Column(name = "`TEMPLATESEQ`", nullable = true, length = 8)
    public String getTemplateseq() {
        return this.templateseq;
    }

    public void setTemplateseq(String templateseq) {
        this.templateseq = templateseq;
    }

    @Column(name = "`KNTFABSEQ`", nullable = true, scale = 0, precision = 2)
    public Byte getKntfabseq() {
        return this.kntfabseq;
    }

    public void setKntfabseq(Byte kntfabseq) {
        this.kntfabseq = kntfabseq;
    }

    @Column(name = "`SELFBD`", nullable = true, length = 1)
    public String getSelfbd() {
        return this.selfbd;
    }

    public void setSelfbd(String selfbd) {
        this.selfbd = selfbd;
    }

    @Column(name = "`BATHDYE`", nullable = true, length = 1)
    public String getBathdye() {
        return this.bathdye;
    }

    public void setBathdye(String bathdye) {
        this.bathdye = bathdye;
    }

    @Column(name = "`CONTDYE`", nullable = true, length = 1)
    public String getContdye() {
        return this.contdye;
    }

    public void setContdye(String contdye) {
        this.contdye = contdye;
    }

    @Column(name = "`POTDYE`", nullable = true, length = 1)
    public String getPotdye() {
        return this.potdye;
    }

    public void setPotdye(String potdye) {
        this.potdye = potdye;
    }

    @Column(name = "`BESTFABWID`", nullable = true, scale = 1, precision = 4)
    public Float getBestfabwid() {
        return this.bestfabwid;
    }

    public void setBestfabwid(Float bestfabwid) {
        this.bestfabwid = bestfabwid;
    }

    @Column(name = "`NEWTRIMSR`", nullable = true, length = 10)
    public String getNewtrimsr() {
        return this.newtrimsr;
    }

    public void setNewtrimsr(String newtrimsr) {
        this.newtrimsr = newtrimsr;
    }

    @Column(name = "`CMBFLAG`", nullable = true, length = 2)
    public String getCmbflag() {
        return this.cmbflag;
    }

    public void setCmbflag(String cmbflag) {
        this.cmbflag = cmbflag;
    }

    @Column(name = "`RECALCTRIM`", nullable = true, length = 1)
    public String getRecalctrim() {
        return this.recalctrim;
    }

    public void setRecalctrim(String recalctrim) {
        this.recalctrim = recalctrim;
    }

    @Column(name = "`FABSUBCAT`", nullable = true, length = 5)
    public String getFabsubcat() {
        return this.fabsubcat;
    }

    public void setFabsubcat(String fabsubcat) {
        this.fabsubcat = fabsubcat;
    }

    @Column(name = "`STRIPEID`", nullable = true, length = 15)
    public String getStripeid() {
        return this.stripeid;
    }

    public void setStripeid(String stripeid) {
        this.stripeid = stripeid;
    }

    @Column(name = "`FABORIEN`", nullable = true, scale = 0, precision = 2)
    public Byte getFaborien() {
        return this.faborien;
    }

    public void setFaborien(Byte faborien) {
        this.faborien = faborien;
    }

    @Column(name = "`ALOPRTID`", nullable = true, length = 15)
    public String getAloprtid() {
        return this.aloprtid;
    }

    public void setAloprtid(String aloprtid) {
        this.aloprtid = aloprtid;
    }

    @Column(name = "`ALOPRTLCN`", nullable = true, length = 6)
    public String getAloprtlcn() {
        return this.aloprtlcn;
    }

    public void setAloprtlcn(String aloprtlcn) {
        this.aloprtlcn = aloprtlcn;
    }

    @Column(name = "`ALOPVAR`", nullable = true, scale = 0, precision = 3)
    public Short getAlopvar() {
        return this.alopvar;
    }

    public void setAlopvar(Short alopvar) {
        this.alopvar = alopvar;
    }

    @Column(name = "`CUTSTR`", nullable = true, length = 1)
    public String getCutstr() {
        return this.cutstr;
    }

    public void setCutstr(String cutstr) {
        this.cutstr = cutstr;
    }

    @Column(name = "`DESIGNER`", nullable = true, length = 6)
    public String getDesigner() {
        return this.designer;
    }

    public void setDesigner(String designer) {
        this.designer = designer;
    }

    @Column(name = "`RECALCCLRPER`", nullable = true, length = 1)
    public String getRecalcclrper() {
        return this.recalcclrper;
    }

    public void setRecalcclrper(String recalcclrper) {
        this.recalcclrper = recalcclrper;
    }

    @Column(name = "`SKUNO`", nullable = true, length = 20)
    public String getSkuno() {
        return this.skuno;
    }

    public void setSkuno(String skuno) {
        this.skuno = skuno;
    }

    @Column(name = "`NOTDYE`", nullable = true, length = 1)
    public String getNotdye() {
        return this.notdye;
    }

    public void setNotdye(String notdye) {
        this.notdye = notdye;
    }

    @Column(name = "`OLDFABTYP`", nullable = true, length = 7)
    public String getOldfabtyp() {
        return this.oldfabtyp;
    }

    public void setOldfabtyp(String oldfabtyp) {
        this.oldfabtyp = oldfabtyp;
    }

    @Column(name = "`OLDSKUNO`", nullable = true, length = 20)
    public String getOldskuno() {
        return this.oldskuno;
    }

    public void setOldskuno(String oldskuno) {
        this.oldskuno = oldskuno;
    }

    @Column(name = "`NWASTE_AOP`", nullable = true, scale = 2, precision = 6)
    public Float getNwasteAop() {
        return this.nwasteAop;
    }

    public void setNwasteAop(Float nwasteAop) {
        this.nwasteAop = nwasteAop;
    }

    @Column(name = "`FABSTS`", nullable = true, length = 3)
    public String getFabsts() {
        return this.fabsts;
    }

    public void setFabsts(String fabsts) {
        this.fabsts = fabsts;
    }

    @Column(name = "`FSTSID`", nullable = true, length = 6)
    public String getFstsid() {
        return this.fstsid;
    }

    public void setFstsid(String fstsid) {
        this.fstsid = fstsid;
    }

    @Column(name = "`FSTSDATE`", nullable = true)
    public LocalDateTime getFstsdate() {
        return this.fstsdate;
    }

    public void setFstsdate(LocalDateTime fstsdate) {
        this.fstsdate = fstsdate;
    }

    @Column(name = "`FSTSREASCOD`", nullable = true, length = 3)
    public String getFstsreascod() {
        return this.fstsreascod;
    }

    public void setFstsreascod(String fstsreascod) {
        this.fstsreascod = fstsreascod;
    }

    @Column(name = "`RELSTG`", nullable = true, length = 1)
    public String getRelstg() {
        return this.relstg;
    }

    public void setRelstg(String relstg) {
        this.relstg = relstg;
    }

    @Column(name = "`SRC_ORDNUM`", nullable = true, length = 12)
    public String getSrcOrdnum() {
        return this.srcOrdnum;
    }

    public void setSrcOrdnum(String srcOrdnum) {
        this.srcOrdnum = srcOrdnum;
    }

    @Column(name = "`SRC_FABSEQ`", nullable = true, scale = 0, precision = 2)
    public Byte getSrcFabseq() {
        return this.srcFabseq;
    }

    public void setSrcFabseq(Byte srcFabseq) {
        this.srcFabseq = srcFabseq;
    }

    @Column(name = "`SRC_INTREFNO`", nullable = true, length = 10)
    public String getSrcIntrefno() {
        return this.srcIntrefno;
    }

    public void setSrcIntrefno(String srcIntrefno) {
        this.srcIntrefno = srcIntrefno;
    }

    @Column(name = "`SRC_INTREFNO_VER`", nullable = true, scale = 0, precision = 3)
    public Short getSrcIntrefnoVer() {
        return this.srcIntrefnoVer;
    }

    public void setSrcIntrefnoVer(Short srcIntrefnoVer) {
        this.srcIntrefnoVer = srcIntrefnoVer;
    }

    @Column(name = "`SRC_TEMPLATESEQ_VER`", nullable = true, scale = 0, precision = 3)
    public Short getSrcTemplateseqVer() {
        return this.srcTemplateseqVer;
    }

    public void setSrcTemplateseqVer(Short srcTemplateseqVer) {
        this.srcTemplateseqVer = srcTemplateseqVer;
    }

    @Column(name = "`SRC_TEMPLATESEQ_YRNOPT`", nullable = true, scale = 0, precision = 3)
    public Short getSrcTemplateseqYrnopt() {
        return this.srcTemplateseqYrnopt;
    }

    public void setSrcTemplateseqYrnopt(Short srcTemplateseqYrnopt) {
        this.srcTemplateseqYrnopt = srcTemplateseqYrnopt;
    }

    @Column(name = "`SRC_TEMPLATESEQ_YRNOPT_VER`", nullable = true, scale = 0, precision = 3)
    public Short getSrcTemplateseqYrnoptVer() {
        return this.srcTemplateseqYrnoptVer;
    }

    public void setSrcTemplateseqYrnoptVer(Short srcTemplateseqYrnoptVer) {
        this.srcTemplateseqYrnoptVer = srcTemplateseqYrnoptVer;
    }

    @Column(name = "`RECALC_NWASTE_AOP`", nullable = true, length = 1)
    public String getRecalcNwasteAop() {
        return this.recalcNwasteAop;
    }

    public void setRecalcNwasteAop(String recalcNwasteAop) {
        this.recalcNwasteAop = recalcNwasteAop;
    }

    @Column(name = "`TRIMSR_DIMDES`", nullable = true, length = 25)
    public String getTrimsrDimdes() {
        return this.trimsrDimdes;
    }

    public void setTrimsrDimdes(String trimsrDimdes) {
        this.trimsrDimdes = trimsrDimdes;
    }

    @Column(name = "`TRIMLEN`", nullable = true, scale = 2, precision = 5)
    public Float getTrimlen() {
        return this.trimlen;
    }

    public void setTrimlen(Float trimlen) {
        this.trimlen = trimlen;
    }

    @Column(name = "`SELVWDTH`", nullable = true, scale = 1, precision = 5)
    public Float getSelvwdth() {
        return this.selvwdth;
    }

    public void setSelvwdth(Float selvwdth) {
        this.selvwdth = selvwdth;
    }

    @Column(name = "`HEATSETREQ`", nullable = true, length = 1)
    public String getHeatsetreq() {
        return this.heatsetreq;
    }

    public void setHeatsetreq(String heatsetreq) {
        this.heatsetreq = heatsetreq;
    }

    @Column(name = "`RESIDUALWDTH`", nullable = true, scale = 1, precision = 5)
    public Float getResidualwdth() {
        return this.residualwdth;
    }

    public void setResidualwdth(Float residualwdth) {
        this.residualwdth = residualwdth;
    }

    @Column(name = "`OPENCOMPACTREQ`", nullable = true, length = 1)
    public String getOpencompactreq() {
        return this.opencompactreq;
    }

    public void setOpencompactreq(String opencompactreq) {
        this.opencompactreq = opencompactreq;
    }

    @Column(name = "`CUTSPREADWDTH_PERCENT_DIFF`", nullable = true, scale = 2, precision = 5)
    public Float getCutspreadwdthPercentDiff() {
        return this.cutspreadwdthPercentDiff;
    }

    public void setCutspreadwdthPercentDiff(Float cutspreadwdthPercentDiff) {
        this.cutspreadwdthPercentDiff = cutspreadwdthPercentDiff;
    }

    @Column(name = "`CUTBORDERWDTH`", nullable = true, scale = 1, precision = 5)
    public Float getCutborderwdth() {
        return this.cutborderwdth;
    }

    public void setCutborderwdth(Float cutborderwdth) {
        this.cutborderwdth = cutborderwdth;
    }

    @Column(name = "`LOTNO`", nullable = true, length = 15)
    public String getLotno() {
        return this.lotno;
    }

    public void setLotno(String lotno) {
        this.lotno = lotno;
    }

    @Column(name = "`LOTSEQ`", nullable = true, scale = 0, precision = 3)
    public Short getLotseq() {
        return this.lotseq;
    }

    public void setLotseq(Short lotseq) {
        this.lotseq = lotseq;
    }

    @Column(name = "`DYETESTREQ`", nullable = true, length = 15)
    public String getDyetestreq() {
        return this.dyetestreq;
    }

    public void setDyetestreq(String dyetestreq) {
        this.dyetestreq = dyetestreq;
    }

    @Column(name = "`DYETESTSEQ`", nullable = true, scale = 0, precision = 2)
    public Byte getDyetestseq() {
        return this.dyetestseq;
    }

    public void setDyetestseq(Byte dyetestseq) {
        this.dyetestseq = dyetestseq;
    }

    @Column(name = "`ANIMONFAB`", nullable = true, length = 2)
    public String getAnimonfab() {
        return this.animonfab;
    }

    public void setAnimonfab(String animonfab) {
        this.animonfab = animonfab;
    }

    @Column(name = "`DSGREQ_PROPOSALOPTION`", nullable = true, length = 15)
    public String getDsgreqProposaloption() {
        return this.dsgreqProposaloption;
    }

    public void setDsgreqProposaloption(String dsgreqProposaloption) {
        this.dsgreqProposaloption = dsgreqProposaloption;
    }

    @Column(name = "`DSGREQ_MODDAT`", nullable = true)
    public LocalDateTime getDsgreqModdat() {
        return this.dsgreqModdat;
    }

    public void setDsgreqModdat(LocalDateTime dsgreqModdat) {
        this.dsgreqModdat = dsgreqModdat;
    }

    @Column(name = "`DSGREQ_MODBY`", nullable = true, length = 6)
    public String getDsgreqModby() {
        return this.dsgreqModby;
    }

    public void setDsgreqModby(String dsgreqModby) {
        this.dsgreqModby = dsgreqModby;
    }

    @Column(name = "`FACESIDE`", nullable = true, length = 2)
    public String getFaceside() {
        return this.faceside;
    }

    public void setFaceside(String faceside) {
        this.faceside = faceside;
    }

    @Column(name = "`MARKERTYP`", nullable = true, length = 2)
    public String getMarkertyp() {
        return this.markertyp;
    }

    public void setMarkertyp(String markertyp) {
        this.markertyp = markertyp;
    }

    @Column(name = "`BASEHANGER_SRCREFREQ`", nullable = true, length = 1)
    public String getBasehangerSrcrefreq() {
        return this.basehangerSrcrefreq;
    }

    public void setBasehangerSrcrefreq(String basehangerSrcrefreq) {
        this.basehangerSrcrefreq = basehangerSrcrefreq;
    }

    @Column(name = "`BASEHANGER_SRCREFORDNUM`", nullable = true, length = 12)
    public String getBasehangerSrcrefordnum() {
        return this.basehangerSrcrefordnum;
    }

    public void setBasehangerSrcrefordnum(String basehangerSrcrefordnum) {
        this.basehangerSrcrefordnum = basehangerSrcrefordnum;
    }

    @Column(name = "`BASEHANGER_SRCREFFABSEQ`", nullable = true, scale = 0, precision = 2)
    public Byte getBasehangerSrcreffabseq() {
        return this.basehangerSrcreffabseq;
    }

    public void setBasehangerSrcreffabseq(Byte basehangerSrcreffabseq) {
        this.basehangerSrcreffabseq = basehangerSrcreffabseq;
    }

    @Column(name = "`UINIRTO_INDICATIVE`", nullable = true, scale = 4, precision = 8)
    public Double getUinirtoIndicative() {
        return this.uinirtoIndicative;
    }

    public void setUinirtoIndicative(Double uinirtoIndicative) {
        this.uinirtoIndicative = uinirtoIndicative;
    }

    @Column(name = "`KINIRTO_INDICATIVE`", nullable = true, scale = 2, precision = 6)
    public Float getKinirtoIndicative() {
        return this.kinirtoIndicative;
    }

    public void setKinirtoIndicative(Float kinirtoIndicative) {
        this.kinirtoIndicative = kinirtoIndicative;
    }

    @Column(name = "`INIRTO_INDICATIVE_REASON`", nullable = true, length = 2)
    public String getInirtoIndicativeReason() {
        return this.inirtoIndicativeReason;
    }

    public void setInirtoIndicativeReason(String inirtoIndicativeReason) {
        this.inirtoIndicativeReason = inirtoIndicativeReason;
    }

    @Column(name = "`SKEWANGLE`", nullable = true, scale = 0, precision = 2)
    public Byte getSkewangle() {
        return this.skewangle;
    }

    public void setSkewangle(Byte skewangle) {
        this.skewangle = skewangle;
    }

    @Column(name = "`STEPHGT`", nullable = true, scale = 2, precision = 6)
    public Float getStephgt() {
        return this.stephgt;
    }

    public void setStephgt(Float stephgt) {
        this.stephgt = stephgt;
    }

    @Column(name = "`SKEWWASTE`", nullable = true, scale = 2, precision = 8)
    public Double getSkewwaste() {
        return this.skewwaste;
    }

    public void setSkewwaste(Double skewwaste) {
        this.skewwaste = skewwaste;
    }

    @Column(name = "`BODYLEN`", nullable = true, scale = 2, precision = 6)
    public Float getBodylen() {
        return this.bodylen;
    }

    public void setBodylen(Float bodylen) {
        this.bodylen = bodylen;
    }

    @Column(name = "`TIGHTNESS`", nullable = true, scale = 1, precision = 4)
    public Float getTightness() {
        return this.tightness;
    }

    public void setTightness(Float tightness) {
        this.tightness = tightness;
    }

    @Column(name = "`FABCPS_BSF`", nullable = true, length = 100)
    public String getFabcpsBsf() {
        return this.fabcpsBsf;
    }

    public void setFabcpsBsf(String fabcpsBsf) {
        this.fabcpsBsf = fabcpsBsf;
    }

    @Column(name = "`FABCPS`", nullable = true, length = 100)
    public String getFabcps() {
        return this.fabcps;
    }

    public void setFabcps(String fabcps) {
        this.fabcps = fabcps;
    }

    @Column(name = "`FABCPS_CLIENT`", nullable = true, length = 100)
    public String getFabcpsClient() {
        return this.fabcpsClient;
    }

    public void setFabcpsClient(String fabcpsClient) {
        this.fabcpsClient = fabcpsClient;
    }

    @Column(name = "`FABCPS_RECALC`", nullable = true, length = 1)
    public String getFabcpsRecalc() {
        return this.fabcpsRecalc;
    }

    public void setFabcpsRecalc(String fabcpsRecalc) {
        this.fabcpsRecalc = fabcpsRecalc;
    }

    @Column(name = "`CMBFABSEQ`", nullable = true, scale = 0, precision = 2)
    public Byte getCmbfabseq() {
        return this.cmbfabseq;
    }

    public void setCmbfabseq(Byte cmbfabseq) {
        this.cmbfabseq = cmbfabseq;
    }

    @Column(name = "`THERMOBD_IND`", nullable = true, length = 1)
    public String getThermobdInd() {
        return this.thermobdInd;
    }

    public void setThermobdInd(String thermobdInd) {
        this.thermobdInd = thermobdInd;
    }

    @Column(name = "`FABDCODELIST`", nullable = true, length = 200)
    public String getFabdcodelist() {
        return this.fabdcodelist;
    }

    public void setFabdcodelist(String fabdcodelist) {
        this.fabdcodelist = fabdcodelist;
    }

    @Column(name = "`LDECOROUTE`", nullable = true, length = 200)
    public String getLdecoroute() {
        return this.ldecoroute;
    }

    public void setLdecoroute(String ldecoroute) {
        this.ldecoroute = ldecoroute;
    }

    @Column(name = "`SDECOROUTE`", nullable = true, length = 150)
    public String getSdecoroute() {
        return this.sdecoroute;
    }

    public void setSdecoroute(String sdecoroute) {
        this.sdecoroute = sdecoroute;
    }

    @Column(name = "`DCCODE`", nullable = true, length = 15)
    public String getDccode() {
        return this.dccode;
    }

    public void setDccode(String dccode) {
        this.dccode = dccode;
    }

    @Column(name = "`CMBFABLAYER`", nullable = true, scale = 0, precision = 1)
    public Byte getCmbfablayer() {
        return this.cmbfablayer;
    }

    public void setCmbfablayer(Byte cmbfablayer) {
        this.cmbfablayer = cmbfablayer;
    }

    @Column(name = "`METHODSEQ`", nullable = true, length = 7)
    public String getMethodseq() {
        return this.methodseq;
    }

    public void setMethodseq(String methodseq) {
        this.methodseq = methodseq;
    }

    @Column(name = "`SKUMATSEQ`", nullable = true, scale = 0, precision = 3)
    public Short getSkumatseq() {
        return this.skumatseq;
    }

    public void setSkumatseq(Short skumatseq) {
        this.skumatseq = skumatseq;
    }

    @Column(name = "`DYEMETHODCOD`", nullable = true, length = 10)
    public String getDyemethodcod() {
        return this.dyemethodcod;
    }

    public void setDyemethodcod(String dyemethodcod) {
        this.dyemethodcod = dyemethodcod;
    }

    @Column(name = "`SKUMATRIXID`", nullable = true, length = 30)
    public String getSkumatrixid() {
        return this.skumatrixid;
    }

    public void setSkumatrixid(String skumatrixid) {
        this.skumatrixid = skumatrixid;
    }

    @Column(name = "`DYECTYCOD`", nullable = true, length = 3)
    public String getDyectycod() {
        return this.dyectycod;
    }

    public void setDyectycod(String dyectycod) {
        this.dyectycod = dyectycod;
    }

    @Column(name = "`USABLEWID_FABOPTRECALC`", nullable = true, length = 1)
    public String getUsablewidFaboptrecalc() {
        return this.usablewidFaboptrecalc;
    }

    public void setUsablewidFaboptrecalc(String usablewidFaboptrecalc) {
        this.usablewidFaboptrecalc = usablewidFaboptrecalc;
    }

    @Column(name = "`USABLEWID_ADYEFN`", nullable = true, scale = 1, precision = 4)
    public Float getUsablewidAdyefn() {
        return this.usablewidAdyefn;
    }

    public void setUsablewidAdyefn(Float usablewidAdyefn) {
        this.usablewidAdyefn = usablewidAdyefn;
    }

    @Column(name = "`USABLEWID_ASKEW`", nullable = true, scale = 1, precision = 4)
    public Float getUsablewidAskew() {
        return this.usablewidAskew;
    }

    public void setUsablewidAskew(Float usablewidAskew) {
        this.usablewidAskew = usablewidAskew;
    }

    @Column(name = "`USABLEWID_AMLF`", nullable = true, scale = 1, precision = 4)
    public Float getUsablewidAmlf() {
        return this.usablewidAmlf;
    }

    public void setUsablewidAmlf(Float usablewidAmlf) {
        this.usablewidAmlf = usablewidAmlf;
    }

    @Column(name = "`MATNOTDYE`", nullable = true, length = 1)
    public String getMatnotdye() {
        return this.matnotdye;
    }

    public void setMatnotdye(String matnotdye) {
        this.matnotdye = matnotdye;
    }

    @Column(name = "`KNRBP`", nullable = true, scale = 2, precision = 5)
    public Float getKnrbp() {
        return this.knrbp;
    }

    public void setKnrbp(Float knrbp) {
        this.knrbp = knrbp;
    }

    @Column(name = "`KNDYETYP`", nullable = true, length = 500)
    public String getKndyetyp() {
        return this.kndyetyp;
    }

    public void setKndyetyp(String kndyetyp) {
        this.kndyetyp = kndyetyp;
    }

    @Column(name = "`DRDYETYP`", nullable = true, length = 2)
    public String getDrdyetyp() {
        return this.drdyetyp;
    }

    public void setDrdyetyp(String drdyetyp) {
        this.drdyetyp = drdyetyp;
    }

    @Column(name = "`CMBTARGFABSEQ`", nullable = true, scale = 0, precision = 2)
    public Byte getCmbtargfabseq() {
        return this.cmbtargfabseq;
    }

    public void setCmbtargfabseq(Byte cmbtargfabseq) {
        this.cmbtargfabseq = cmbtargfabseq;
    }

    @Column(name = "`TECHCODE`", nullable = true, length = 15)
    public String getTechcode() {
        return this.techcode;
    }

    public void setTechcode(String techcode) {
        this.techcode = techcode;
    }

    @Column(name = "`TECHVAR`", nullable = true, scale = 0, precision = 3)
    public Short getTechvar() {
        return this.techvar;
    }

    public void setTechvar(Short techvar) {
        this.techvar = techvar;
    }

    @Column(name = "`TECHPLACEMENT`", nullable = true, length = 3)
    public String getTechplacement() {
        return this.techplacement;
    }

    public void setTechplacement(String techplacement) {
        this.techplacement = techplacement;
    }

    @Column(name = "`AOPSTRIKEOFF`", nullable = true, length = 1)
    public String getAopstrikeoff() {
        return this.aopstrikeoff;
    }

    public void setAopstrikeoff(String aopstrikeoff) {
        this.aopstrikeoff = aopstrikeoff;
    }

    @Column(name = "`AOPSTRIKEOFFBY`", nullable = true, length = 6)
    public String getAopstrikeoffby() {
        return this.aopstrikeoffby;
    }

    public void setAopstrikeoffby(String aopstrikeoffby) {
        this.aopstrikeoffby = aopstrikeoffby;
    }

    @Column(name = "`AOPSTRIKEOFFDATE`", nullable = true)
    public LocalDateTime getAopstrikeoffdate() {
        return this.aopstrikeoffdate;
    }

    public void setAopstrikeoffdate(LocalDateTime aopstrikeoffdate) {
        this.aopstrikeoffdate = aopstrikeoffdate;
    }

    @Column(name = "`YDCALC_PREVSTS`", nullable = true, length = 3)
    public String getYdcalcPrevsts() {
        return this.ydcalcPrevsts;
    }

    public void setYdcalcPrevsts(String ydcalcPrevsts) {
        this.ydcalcPrevsts = ydcalcPrevsts;
    }

    @Column(name = "`YDCALC_PREVSTSBY`", nullable = true, length = 6)
    public String getYdcalcPrevstsby() {
        return this.ydcalcPrevstsby;
    }

    public void setYdcalcPrevstsby(String ydcalcPrevstsby) {
        this.ydcalcPrevstsby = ydcalcPrevstsby;
    }

    @Column(name = "`YDCALC_PREVSTSDATE`", nullable = true)
    public LocalDateTime getYdcalcPrevstsdate() {
        return this.ydcalcPrevstsdate;
    }

    public void setYdcalcPrevstsdate(LocalDateTime ydcalcPrevstsdate) {
        this.ydcalcPrevstsdate = ydcalcPrevstsdate;
    }

    @Column(name = "`YDCALC_STS`", nullable = true, length = 3)
    public String getYdcalcSts() {
        return this.ydcalcSts;
    }

    public void setYdcalcSts(String ydcalcSts) {
        this.ydcalcSts = ydcalcSts;
    }

    @Column(name = "`YDCALC_STSBY`", nullable = true, length = 6)
    public String getYdcalcStsby() {
        return this.ydcalcStsby;
    }

    public void setYdcalcStsby(String ydcalcStsby) {
        this.ydcalcStsby = ydcalcStsby;
    }

    @Column(name = "`YDCALC_STSDATE`", nullable = true)
    public LocalDateTime getYdcalcStsdate() {
        return this.ydcalcStsdate;
    }

    public void setYdcalcStsdate(LocalDateTime ydcalcStsdate) {
        this.ydcalcStsdate = ydcalcStsdate;
    }

    @Column(name = "`YDCALC_REPEAT`", nullable = true, scale = 2, precision = 5)
    public Float getYdcalcRepeat() {
        return this.ydcalcRepeat;
    }

    public void setYdcalcRepeat(Float ydcalcRepeat) {
        this.ydcalcRepeat = ydcalcRepeat;
    }

    @Column(name = "`YDCALC_FULLFEED`", nullable = true, scale = 2, precision = 5)
    public Float getYdcalcFullfeed() {
        return this.ydcalcFullfeed;
    }

    public void setYdcalcFullfeed(Float ydcalcFullfeed) {
        this.ydcalcFullfeed = ydcalcFullfeed;
    }

    @Column(name = "`PATFABTYP`", nullable = true, length = 15)
    public String getPatfabtyp() {
        return this.patfabtyp;
    }

    public void setPatfabtyp(String patfabtyp) {
        this.patfabtyp = patfabtyp;
    }

    @Column(name = "`FABDET_RECALC`", nullable = true, length = 1)
    public String getFabdetRecalc() {
        return this.fabdetRecalc;
    }

    public void setFabdetRecalc(String fabdetRecalc) {
        this.fabdetRecalc = fabdetRecalc;
    }

    @Column(name = "`SRC_FABMODIND`", nullable = true, length = 1)
    public String getSrcFabmodind() {
        return this.srcFabmodind;
    }

    public void setSrcFabmodind(String srcFabmodind) {
        this.srcFabmodind = srcFabmodind;
    }

    @Column(name = "`KNTCTYCOD`", nullable = true, length = 3)
    public String getKntctycod() {
        return this.kntctycod;
    }

    public void setKntctycod(String kntctycod) {
        this.kntctycod = kntctycod;
    }

    @Column(name = "`FABBASENO`", nullable = true, length = 50)
    public String getFabbaseno() {
        return this.fabbaseno;
    }

    public void setFabbaseno(String fabbaseno) {
        this.fabbaseno = fabbaseno;
    }

    @Column(name = "`DCCODE_RECALC`", nullable = true, length = 1)
    public String getDccodeRecalc() {
        return this.dccodeRecalc;
    }

    public void setDccodeRecalc(String dccodeRecalc) {
        this.dccodeRecalc = dccodeRecalc;
    }

    @Column(name = "`FABBASEYRN_RECALC`", nullable = true, length = 1)
    public String getFabbaseyrnRecalc() {
        return this.fabbaseyrnRecalc;
    }

    public void setFabbaseyrnRecalc(String fabbaseyrnRecalc) {
        this.fabbaseyrnRecalc = fabbaseyrnRecalc;
    }

    @Column(name = "`FABBASE_DEVIND`", nullable = true, length = 1)
    public String getFabbaseDevind() {
        return this.fabbaseDevind;
    }

    public void setFabbaseDevind(String fabbaseDevind) {
        this.fabbaseDevind = fabbaseDevind;
    }

    @Column(name = "`BASEHANGER_SRCNOTREQ`", nullable = true, length = 1)
    public String getBasehangerSrcnotreq() {
        return this.basehangerSrcnotreq;
    }

    public void setBasehangerSrcnotreq(String basehangerSrcnotreq) {
        this.basehangerSrcnotreq = basehangerSrcnotreq;
    }

    @Column(name = "`BASEHANGER_SRCREQIND_MODID`", nullable = true, length = 6)
    public String getBasehangerSrcreqindModid() {
        return this.basehangerSrcreqindModid;
    }

    public void setBasehangerSrcreqindModid(String basehangerSrcreqindModid) {
        this.basehangerSrcreqindModid = basehangerSrcreqindModid;
    }

    @Column(name = "`BASEHANGER_SRCREQIND_MODDAT`", nullable = true)
    public LocalDateTime getBasehangerSrcreqindModdat() {
        return this.basehangerSrcreqindModdat;
    }

    public void setBasehangerSrcreqindModdat(LocalDateTime basehangerSrcreqindModdat) {
        this.basehangerSrcreqindModdat = basehangerSrcreqindModdat;
    }

    @Column(name = "`BASEHANGER_SRCREFAPVIND`", nullable = true, length = 1)
    public String getBasehangerSrcrefapvind() {
        return this.basehangerSrcrefapvind;
    }

    public void setBasehangerSrcrefapvind(String basehangerSrcrefapvind) {
        this.basehangerSrcrefapvind = basehangerSrcrefapvind;
    }

    @Column(name = "`AOPSTRIKEOFF_REQUIRED`", nullable = true, length = 1)
    public String getAopstrikeoffRequired() {
        return this.aopstrikeoffRequired;
    }

    public void setAopstrikeoffRequired(String aopstrikeoffRequired) {
        this.aopstrikeoffRequired = aopstrikeoffRequired;
    }

    @Column(name = "`AOPSTRIKEOFF_NOTREQUIRED`", nullable = true, length = 1)
    public String getAopstrikeoffNotrequired() {
        return this.aopstrikeoffNotrequired;
    }

    public void setAopstrikeoffNotrequired(String aopstrikeoffNotrequired) {
        this.aopstrikeoffNotrequired = aopstrikeoffNotrequired;
    }

    @Column(name = "`AOPSTRIKEOFF_AOPCODE`", nullable = true, length = 15)
    public String getAopstrikeoffAopcode() {
        return this.aopstrikeoffAopcode;
    }

    public void setAopstrikeoffAopcode(String aopstrikeoffAopcode) {
        this.aopstrikeoffAopcode = aopstrikeoffAopcode;
    }

    @Column(name = "`AOPSTRIKEOFF_AOPVAR`", nullable = true, scale = 0, precision = 3)
    public Short getAopstrikeoffAopvar() {
        return this.aopstrikeoffAopvar;
    }

    public void setAopstrikeoffAopvar(Short aopstrikeoffAopvar) {
        this.aopstrikeoffAopvar = aopstrikeoffAopvar;
    }

    @Column(name = "`AOPSTRIKEOFF_MODBY`", nullable = true, length = 6)
    public String getAopstrikeoffModby() {
        return this.aopstrikeoffModby;
    }

    public void setAopstrikeoffModby(String aopstrikeoffModby) {
        this.aopstrikeoffModby = aopstrikeoffModby;
    }

    @Column(name = "`AOPSTRIKEOFF_MODDATE`", nullable = true)
    public LocalDateTime getAopstrikeoffModdate() {
        return this.aopstrikeoffModdate;
    }

    public void setAopstrikeoffModdate(LocalDateTime aopstrikeoffModdate) {
        this.aopstrikeoffModdate = aopstrikeoffModdate;
    }

    @Column(name = "`AOPSTRIKEOFF_SRCREFORDNUM`", nullable = true, length = 12)
    public String getAopstrikeoffSrcrefordnum() {
        return this.aopstrikeoffSrcrefordnum;
    }

    public void setAopstrikeoffSrcrefordnum(String aopstrikeoffSrcrefordnum) {
        this.aopstrikeoffSrcrefordnum = aopstrikeoffSrcrefordnum;
    }

    @Column(name = "`AOPSTRIKEOFF_SRCREFFABSEQ`", nullable = true, scale = 0, precision = 2)
    public Byte getAopstrikeoffSrcreffabseq() {
        return this.aopstrikeoffSrcreffabseq;
    }

    public void setAopstrikeoffSrcreffabseq(Byte aopstrikeoffSrcreffabseq) {
        this.aopstrikeoffSrcreffabseq = aopstrikeoffSrcreffabseq;
    }

    @Column(name = "`AOPSTRIKEOFF_APVIND`", nullable = true, length = 1)
    public String getAopstrikeoffApvind() {
        return this.aopstrikeoffApvind;
    }

    public void setAopstrikeoffApvind(String aopstrikeoffApvind) {
        this.aopstrikeoffApvind = aopstrikeoffApvind;
    }

    @Column(name = "`INTFABCERTNO`", nullable = true, length = 50)
    public String getIntfabcertno() {
        return this.intfabcertno;
    }

    public void setIntfabcertno(String intfabcertno) {
        this.intfabcertno = intfabcertno;
    }

    @Column(name = "`INTFABCERTNO_FIXEDIND`", nullable = true, length = 1)
    public String getIntfabcertnoFixedind() {
        return this.intfabcertnoFixedind;
    }

    public void setIntfabcertnoFixedind(String intfabcertnoFixedind) {
        this.intfabcertnoFixedind = intfabcertnoFixedind;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Ort120)) return false;
        final Ort120 ort120 = (Ort120) o;
        return Objects.equals(getOrdnum(), ort120.getOrdnum()) &&
                Objects.equals(getFabseq(), ort120.getFabseq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getFabseq());
    }
}