/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class Ort120Id implements Serializable {

    private String ordnum;
    private Byte fabseq;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Ort120)) return false;
        final Ort120 ort120 = (Ort120) o;
        return Objects.equals(getOrdnum(), ort120.getOrdnum()) &&
                Objects.equals(getFabseq(), ort120.getFabseq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getFabseq());
    }
}