/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Ttt1010 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TTT1010`")
public class Ttt1010 implements Serializable {

    private String intrefno;
    private String fabmodby;
    private LocalDateTime fabmoddat;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] fabphoto;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] fabthumb;

    @Id
    @Column(name = "`INTREFNO`", nullable = false, length = 10)
    public String getIntrefno() {
        return this.intrefno;
    }

    public void setIntrefno(String intrefno) {
        this.intrefno = intrefno;
    }

    @Column(name = "`FABMODBY`", nullable = true, length = 6)
    public String getFabmodby() {
        return this.fabmodby;
    }

    public void setFabmodby(String fabmodby) {
        this.fabmodby = fabmodby;
    }

    @Column(name = "`FABMODDAT`", nullable = true)
    public LocalDateTime getFabmoddat() {
        return this.fabmoddat;
    }

    public void setFabmoddat(LocalDateTime fabmoddat) {
        this.fabmoddat = fabmoddat;
    }

    @Column(name = "`FABPHOTO`", nullable = true)
    public byte[] getFabphoto() {
        return this.fabphoto;
    }

    public void setFabphoto(byte[] fabphoto) {
        this.fabphoto = fabphoto;
    }

    @Column(name = "`FABTHUMB`", nullable = true)
    public byte[] getFabthumb() {
        return this.fabthumb;
    }

    public void setFabthumb(byte[] fabthumb) {
        this.fabthumb = fabthumb;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Ttt1010)) return false;
        final Ttt1010 ttt1010 = (Ttt1010) o;
        return Objects.equals(getIntrefno(), ttt1010.getIntrefno());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIntrefno());
    }
}