/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Ttt1030 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TTT1030`")
public class Ttt1030 implements Serializable {

    private Long docid;
    private String fabdevno;
    private String doctype;
    private String filename;
    private String remarks;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] docfile;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] docthumb;
    private String mimetype;
    private String uploadby;
    private LocalDateTime uploaddate;

    @Id
    @Column(name = "`DOCID`", nullable = false, scale = 0, precision = 16)
    public Long getDocid() {
        return this.docid;
    }

    public void setDocid(Long docid) {
        this.docid = docid;
    }

    @Column(name = "`FABDEVNO`", nullable = false, length = 15)
    public String getFabdevno() {
        return this.fabdevno;
    }

    public void setFabdevno(String fabdevno) {
        this.fabdevno = fabdevno;
    }

    @Column(name = "`DOCTYPE`", nullable = true, length = 20)
    public String getDoctype() {
        return this.doctype;
    }

    public void setDoctype(String doctype) {
        this.doctype = doctype;
    }

    @Column(name = "`FILENAME`", nullable = true, length = 100)
    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Column(name = "`REMARKS`", nullable = true, length = 256)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "`DOCFILE`", nullable = true)
    public byte[] getDocfile() {
        return this.docfile;
    }

    public void setDocfile(byte[] docfile) {
        this.docfile = docfile;
    }

    @Column(name = "`DOCTHUMB`", nullable = true)
    public byte[] getDocthumb() {
        return this.docthumb;
    }

    public void setDocthumb(byte[] docthumb) {
        this.docthumb = docthumb;
    }

    @Column(name = "`MIMETYPE`", nullable = true, length = 25)
    public String getMimetype() {
        return this.mimetype;
    }

    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    @Column(name = "`UPLOADBY`", nullable = true, length = 20)
    public String getUploadby() {
        return this.uploadby;
    }

    public void setUploadby(String uploadby) {
        this.uploadby = uploadby;
    }

    @Column(name = "`UPLOADDATE`", nullable = true)
    public LocalDateTime getUploaddate() {
        return this.uploaddate;
    }

    public void setUploaddate(LocalDateTime uploaddate) {
        this.uploaddate = uploaddate;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Ttt1030)) return false;
        final Ttt1030 ttt1030 = (Ttt1030) o;
        return Objects.equals(getDocid(), ttt1030.getDocid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDocid());
    }
}