/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryFabSubCatResponse implements Serializable {


    @ColumnAlias("FABTYP")
    private String fabtyp;

    @ColumnAlias("FABSUBCAT")
    private String fabsubcat;

    @ColumnAlias("SUBCATDES")
    private String subcatdes;

    public String getFabtyp() {
        return this.fabtyp;
    }

    public void setFabtyp(String fabtyp) {
        this.fabtyp = fabtyp;
    }

    public String getFabsubcat() {
        return this.fabsubcat;
    }

    public void setFabsubcat(String fabsubcat) {
        this.fabsubcat = fabsubcat;
    }

    public String getSubcatdes() {
        return this.subcatdes;
    }

    public void setSubcatdes(String subcatdes) {
        this.subcatdes = subcatdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryFabSubCatResponse)) return false;
        final QryFabSubCatResponse qryFabSubCatResponse = (QryFabSubCatResponse) o;
        return Objects.equals(getFabtyp(), qryFabSubCatResponse.getFabtyp()) &&
                Objects.equals(getFabsubcat(), qryFabSubCatResponse.getFabsubcat()) &&
                Objects.equals(getSubcatdes(), qryFabSubCatResponse.getSubcatdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFabtyp(),
                getFabsubcat(),
                getSubcatdes());
    }
}