/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryStrLcnCodResponse implements Serializable {


    @ColumnAlias("ITEMDES")
    private String itemdes;

    public String getItemdes() {
        return this.itemdes;
    }

    public void setItemdes(String itemdes) {
        this.itemdes = itemdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryStrLcnCodResponse)) return false;
        final QryStrLcnCodResponse qryStrLcnCodResponse = (QryStrLcnCodResponse) o;
        return Objects.equals(getItemdes(), qryStrLcnCodResponse.getItemdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getItemdes());
    }
}