/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryStrCodLcnResponse implements Serializable {


    @ColumnAlias("ITEMDES")
    private String itemdes;

    @ColumnAlias("ITEMCOD")
    private String itemcod;

    public String getItemdes() {
        return this.itemdes;
    }

    public void setItemdes(String itemdes) {
        this.itemdes = itemdes;
    }

    public String getItemcod() {
        return this.itemcod;
    }

    public void setItemcod(String itemcod) {
        this.itemcod = itemcod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryStrCodLcnResponse)) return false;
        final QryStrCodLcnResponse qryStrCodLcnResponse = (QryStrCodLcnResponse) o;
        return Objects.equals(getItemdes(), qryStrCodLcnResponse.getItemdes()) &&
                Objects.equals(getItemcod(), qryStrCodLcnResponse.getItemcod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getItemdes(),
                getItemcod());
    }
}