/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryYarnIdResponse implements Serializable {


    @ColumnAlias("SEQNUM")
    private Byte seqnum;

    @ColumnAlias("YRNLOT")
    private String yrnlot;

    @ColumnAlias("YRNORI")
    private String yrnori;

    @ColumnAlias("YRNCNT")
    private String yrncnt;

    @ColumnAlias("YRNCPS")
    private String yrncps;

    @ColumnAlias("YRNCLR")
    private String yrnclr;

    @ColumnAlias("YRNFRAC")
    private Short yrnfrac;

    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("YRNQLTY")
    private String yrnqlty;

    @ColumnAlias("YRNSUBQLTYA")
    private String yrnsubqltya;

    @ColumnAlias("YRNSUBQLTYB")
    private String yrnsubqltyb;

    @ColumnAlias("YRNFF")
    private String yrnff;

    public Byte getSeqnum() {
        return this.seqnum;
    }

    public void setSeqnum(Byte seqnum) {
        this.seqnum = seqnum;
    }

    public String getYrnlot() {
        return this.yrnlot;
    }

    public void setYrnlot(String yrnlot) {
        this.yrnlot = yrnlot;
    }

    public String getYrnori() {
        return this.yrnori;
    }

    public void setYrnori(String yrnori) {
        this.yrnori = yrnori;
    }

    public String getYrncnt() {
        return this.yrncnt;
    }

    public void setYrncnt(String yrncnt) {
        this.yrncnt = yrncnt;
    }

    public String getYrncps() {
        return this.yrncps;
    }

    public void setYrncps(String yrncps) {
        this.yrncps = yrncps;
    }

    public String getYrnclr() {
        return this.yrnclr;
    }

    public void setYrnclr(String yrnclr) {
        this.yrnclr = yrnclr;
    }

    public Short getYrnfrac() {
        return this.yrnfrac;
    }

    public void setYrnfrac(Short yrnfrac) {
        this.yrnfrac = yrnfrac;
    }

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public String getYrnqlty() {
        return this.yrnqlty;
    }

    public void setYrnqlty(String yrnqlty) {
        this.yrnqlty = yrnqlty;
    }

    public String getYrnsubqltya() {
        return this.yrnsubqltya;
    }

    public void setYrnsubqltya(String yrnsubqltya) {
        this.yrnsubqltya = yrnsubqltya;
    }

    public String getYrnsubqltyb() {
        return this.yrnsubqltyb;
    }

    public void setYrnsubqltyb(String yrnsubqltyb) {
        this.yrnsubqltyb = yrnsubqltyb;
    }

    public String getYrnff() {
        return this.yrnff;
    }

    public void setYrnff(String yrnff) {
        this.yrnff = yrnff;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryYarnIdResponse)) return false;
        final QryYarnIdResponse qryYarnIdResponse = (QryYarnIdResponse) o;
        return Objects.equals(getSeqnum(), qryYarnIdResponse.getSeqnum()) &&
                Objects.equals(getYrnlot(), qryYarnIdResponse.getYrnlot()) &&
                Objects.equals(getYrnori(), qryYarnIdResponse.getYrnori()) &&
                Objects.equals(getYrncnt(), qryYarnIdResponse.getYrncnt()) &&
                Objects.equals(getYrncps(), qryYarnIdResponse.getYrncps()) &&
                Objects.equals(getYrnclr(), qryYarnIdResponse.getYrnclr()) &&
                Objects.equals(getYrnfrac(), qryYarnIdResponse.getYrnfrac()) &&
                Objects.equals(getYrncod(), qryYarnIdResponse.getYrncod()) &&
                Objects.equals(getYrnqlty(), qryYarnIdResponse.getYrnqlty()) &&
                Objects.equals(getYrnsubqltya(), qryYarnIdResponse.getYrnsubqltya()) &&
                Objects.equals(getYrnsubqltyb(), qryYarnIdResponse.getYrnsubqltyb()) &&
                Objects.equals(getYrnff(), qryYarnIdResponse.getYrnff());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSeqnum(),
                getYrnlot(),
                getYrnori(),
                getYrncnt(),
                getYrncps(),
                getYrnclr(),
                getYrnfrac(),
                getYrncod(),
                getYrnqlty(),
                getYrnsubqltya(),
                getYrnsubqltyb(),
                getYrnff());
    }
}