/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.mu.cmt.pfs.pfsdb.models.query.*;

public interface PfsdbQueryExecutorService {

    Page<QryStrLcnCodResponse> executeQryStrLcnCod(String strcod, Pageable pageable);

    void exportQryStrLcnCod(String strcod, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryLovSwatchFormatResponse> executeQryLovSwatchFormat(String ppurpose, Pageable pageable);

    void exportQryLovSwatchFormat(String ppurpose, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryGetFabtypResponse> executeQryGetFabtyp(Pageable pageable);

    void exportQryGetFabtyp(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryLovItemsResponse> executeQryLovItems(String plovfld, String ptab, String pshowAll, Pageable pageable);

    void exportQryLovItems(String plovfld, String ptab, String pshowAll, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryWarehouseLocResponse> executeQryWarehouseLoc(String pitemdes3, Pageable pageable);

    void exportQryWarehouseLoc(String pitemdes3, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryStrCodLcnResponse> executeQryStrCodLcn(Pageable pageable);

    void exportQryStrCodLcn(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryFabSubCatResponse> executeQryFabSubCat(Pageable pageable);

    void exportQryFabSubCat(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryStockLocationResponse> executeQryStockLocation(String pstockType, Pageable pageable);

    void exportQryStockLocation(String pstockType, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryYarnIdResponse> executeQryYarnId(String pordnum, Integer pyrnid, Pageable pageable);

    void exportQryYarnId(String pordnum, Integer pyrnid, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryGetThemesResponse> executeQryGetThemes(String ptheme, Pageable pageable);

    void exportQryGetThemes(String ptheme, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}