/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.InputStream;
import java.sql.Date;

import com.mu.cmt.pfs.pfsdb.models.procedure.*;

public interface PfsdbProcedureExecutorService {

    Void executeProcKn1610pk0_updccfUpdRem(String pprgid, String pusrid, String pfabdevno, Integer pfabitemseq, String pccfremarks);

    GetEnzymeResponse executeGetEnzyme();

    GetYrnclrResponse executeGetYrnclr();

    GetYrncntResponse executeGetYrncnt();

    ProcSr741pk0requestSwatchResponse executeProcSr741pk0RequestSwatch(String psorders, String pteam, String pusrid, String pfabformat, String ppurpose, Double pquantity, String puom, String plcnstrcod);

    Void executeProcKn1620pk0_ccfmatchAddCCF(String pprgid, String pusrid, String psintfabcertno, String pmintfabcertno, String pdintfabcertno, String pmatchcat);

    GetYrnffcodResponse executeGetYrnffcod();

    ProcKn1610pk0ExcccfGetOrderStsResponse executeProcKn1610pk0_excccfGetOrderSts(String pprgid, String pordnum, Integer pfabseq);

    ProcKn1620pk0CcfmqryQryCcfResponse executeProcKn1620pk0_ccfmqryQryCCF(String pprgid, String pusrid, String pqrytype, String psintfabcertno, String psordnum, Integer psfabseq, String pmintfabcertno, String pmordnum, Integer pmfabseq, String pmatchcat);

    ProcKn1610pk0ExcccfGetCcflistResponse executeProcKn1610pk0_excccfGetCCFList(String pprgid, String pusrid, String pintfabcertno, String pfabcertsts, Date pstsfromdat, Date pststodat, String pfabtyp, Integer pmchgau, Integer pfabwgt, String pfabcps, String pfabdevno, Date pfabdevnoReqdatfrom, Date pfabdevnoReqdatto, String pordnum, String ptemplateseq);

    ProcKn1610pk0ExccfUpdRelMatrixResponse executeProcKn1610pk0_exccfUpdRelMatrix(String pprgid, String pusrid, String pccfno, String pordFabList);

    ProcFindMatchYrnStockClrResponse executeProcFindMatchYrnStockClr(String pyrncnt, String pcompo, String pyrnCdes, String pyrnQual, String pyrnYrnQualSubA, String pyrnYrnQualSubB, String pyrnffcod, String pyrnLabref, String pyrnlot, String panyColor, Double plabL, Double plabA, Double plabB, Double ptoleranceDeltaE);

    ProcKn1610pk0ExcccfGetRelatedMatrixResponse executeProcKn1610pk0_excccfGetRelatedMatrix(String pprgid, String pusrid, String pordnum, Integer pfabseq, Date prelDateFrom, Date prelDateTo, String pfilterOpt, String pintFabcertno, String ptemplateseq);

    GetOutsideResponse executeGetOutside();

    GetYrnsubqltybResponse executeGetYrnsubqltyb(String pyrnqlty);

    ProcTt130pk0FabdevlibGetOrderDetailsResponse executeProcTT130pk0_fabdevlibGetOrderDetails(String pordnum, Integer pfabseq, String pintfabcertno);

    SprocMatchFabricClrResponse executeSprocMatchFabricClr(String pstore, String pordnum, String pclicod, String pfabtyp, String pfabsubcat, String pskuno, Integer pfabwgtFrom, Integer pfabwgtTo, Integer pbsffabwgtfrom, Integer pbsffabwgtto, Integer pfabwid, String pinside, String poutside, String pcalstn, String pclrref, String pstr, String pstripeId, String ptheme, String penzyme, String pteflon, String pldecoroute, String pfabdcodelist, String pdccode, Integer pmchgaufrom, Integer pmchgauto, String pyrncnt, String pyrncps, String pyrnclr, String poriclr, String pyrnqlty, String pyrnsubqltya, String pyrnsubqltyb, String pyrnffcod, String pyrnClrref, String pcpsField, String pcpstypA, Integer pcpstypAfrom, Integer pcpstypAto, String pcpstypB, Integer pcpstypBfrom, Integer pcpstypBto, String pcpstypC, Integer pcpstypCfrom, Integer pcpstypCto, String psearchColour, Double plabL, Double plabA, Double plabB, Double ptoleranceDeltaE, String puser, String pintfabcertno, String pccfmatchcat, String pwarehouse, String ppatternCode);

    GetYrnsubqltyaResponse executeGetYrnsubqltya(String pyrnqlty);

    GetYrnsubqltycResponse executeGetYrnsubqltyc(String pyrnqlty);

    Void executeUpdateTT130PK0_FABDEVLIB_request_FabSrcMail(UpdateTt130pk0FabdevlibRequestFabSrcMailRequest updateTt130pk0fabdevlibRequestFabSrcMailRequest);

    ProcKn1610pk0ExcccfGetFablibKdsResponse executeProcKn1610pk0_excccfGetFablibKds(String pprgid, String pusrid, String pordnum, Integer pfabseq);

    ProcRf2000pk0OrlovGetCliGrpResponse executeProcRf2000pk0_OrlovGetCliGrp(String pusrid, String pprgid);

    ProcKn1610pk0ExcccfAssociateOrderResponse executeProcKn1610pk0_excccfAssociateOrder(String pprgid, String pusrid, String pordnum, Integer pfabseq, String pccfno);

    ProcKn1610pk0ExcccfGetCcffabDiffResponse executeProcKn1610pk0_excccfGetCCFFabDiff(String pprgid, String pusrid, String pintfabcertno2, String pordnum, Integer pfabseq);

    ProcRf020pk0getClrOptResponse executeProcRf020pk0GetClrOpt(String pclroption, String pfilter);

    ProcTt130pk0FabdevlibGetYrnCpsResponse executeProcTt130pk0_fabdevlibGetYrnCps();

    GetFabdevreqdetResponse executeGetFabdevreqdet(String pfabdevno);

    UpdFabdevnoResponse executeUpdFabdevno(String pfabAssessno, String pfabdevno, String pordnum, Integer pfabseq, String pfabbaseno, String pfabsearchsrc, String pprgid, String pusrid);

    ProcTt130pk0FabdevlibGetFabFilterOptResponse executeProcTt130pk0_fabdevlibGetFabFilterOpt();

    GetYrncdesResponse executeGetYrncdes(String pyrnclr, String pyrncnt);

    ProcRf020pk0QryClrsCompareDeltaEResponse executeProcRf020pk0_QryClrsCompareDeltaE(Double plabL1, Double plabA1, Double plabB1, Double plabL2, Double plabA2, Double plabB2);

    InputStream executeProcSr741pk0SprocGetFabImages(String pordnum, Integer pfabseq);

    ProcRf020pk0UpdClrsAddPantoneResponse executeProcRf020pk0_UpdClrsAddPantone(String pprgid, String puserid, String ppantone, String ppantoneCat, Double plabL, Double plabA, Double plabB, Double prgbR, Double prgbG, Double prgbB, String phexval, String poption);

    GetYrncpstypResponse executeGetYrncpstyp();

    GetSpFinishResponse executeGetSpFinish();

    GetFabtypResponse executeGetFabtyp();

    ProcRf020pk0QryclrsGetColoursResponse executeProcRf020pk0_qryclrsGetColours(Double plabL, Double plabA, Double plabB, Double ptoleranceDeltaE, String psearchOpt, String plabref, String pvalue);

    GetStrResponse executeGetStr();

    GetInsideResponse executeGetInside();

    GetYrnqltyResponse executeGetYrnqlty();

    GetProcTt130pk0FabdevlibClicodResponse executeGetProcTT130PK0_FABDEVLIB_Clicod(String pprgid);

    GetMatchingFabsResponse executeGetMatchingFabs(String pusrid, String pprgid, String pfabFilterOption, String pfabtyp, String pinside, String poutside, String penzyme, String pspfinish, String pstr, String pstripeid, String pdccode, String pldecoroute, String pyarnList, String pyrncnt, String pyrncps, String pyrnclr, String poriclr, String pyrnqlty, String pyrnsubqltya, String pyrnsubqltyb, String pyrnffcod, String pyrnClrref, Integer pfabwgtfrom, Integer pfabwgtto, Integer pbsffabwgtfrom, Integer pbsffabwgtto, Integer pmchgaufrom, Integer pmchgauto, String pcpsField, String pcpstypA, Integer pcpstypAfrom, Integer pcpstypAto, String pcpstypB, Integer pcpstypBfrom, Integer pcpstypBto, String pcpstypC, Integer pcpstypCfrom, Integer pcpstypCto, String pfabdevno, String pordnum, String pfabsubcatdes, String pskuno, String pfabdcodelist, String pcalstn, String pintfabcertno, String porderwithHanger, String pcligrp, String ptemplateSeq);

    GetLdecorouteResponse executeGetLdecoroute();

    ProcKn1610pk0ExcccfProcExcpCertifyFabResponse executeProcKn1610pk0_excccfProcExcpCertifyFab(String pprgid, String pusrid, String pordnum, Integer pfabseq, String pnewsts, String pnewremarks);

    ProcKn1620pk0ccfmQryGetMatchDetResponse executeProcKn1620pk0CcfmQryGetMatchDet(String psintfabcertno, String pdintfabcertno, String pccffilter);

    GetDccodeResponse executeGetDccode();

}